(() => {
  const SS=window.SpellSystem,kinds=['element','shape','elasticity','behavior','control'],colors={element:'#b75646',shape:'#8360af',elasticity:'#347e9b',behavior:'#a67b37',control:'#b88a54',talent:'#5c9c75'},labels={element:'Elements',shape:'Forms',elasticity:'Motion',behavior:'Events',control:'Control',talent:'Talents'};
  let mode='script',category='element',selectedUpgrade=null,insertAt=null,drag=null,rangeStart=null,previewTimer=null;
  const lab=document.createElement('div');lab.id='spellLab';lab.className='lab-overlay hidden';lab.setAttribute('role','dialog');lab.setAttribute('aria-modal','true');lab.setAttribute('aria-label','Spell Lab');
  lab.innerHTML='<div class="lab-window"><div class="lab-header"><div><h2>✦ Spell Lab</h2><p>Connect blocks to write what happens when you cast.</p></div><div class="lab-mode-tabs"><button id="labCodeTab">Code</button><button id="labUpgradeTab">Upgrades</button></div><div class="lab-head-actions"><span class="lab-magic" id="labMagic"></span><button class="lab-close" id="closeLab">Done</button></div></div><div class="lab-body"><div class="lab-categories" id="labCategories"></div><div class="lab-palette"><h3 id="labCategoryTitle"></h3><p id="labPaletteHint"></p><div id="labPaletteBlocks"></div></div><div class="lab-workspace" data-workspace="true" id="labWorkspace"><div id="labWorkContent"></div><div class="lab-tip" id="labTip"></div></div></div></div>';
  document.body.append(lab);const $=id=>document.getElementById(id);
  const byId=id=>SS.block(id)||SS.talents.find(t=>t.id===id);
  function render(){
    $('labMagic').textContent=`✦ ${SS.magic} Magic`;
    $('labCodeTab').classList.toggle('active',mode==='script');$('labUpgradeTab').classList.toggle('active',mode==='upgrades');
    const rail=$('labCategories');rail.innerHTML='';for(const kind of [...kinds,'talent']){if(mode==='script'&&kind==='talent')continue;const b=document.createElement('button');b.className='lab-category'+(category===kind?' active':'');b.style.setProperty('--block-color',colors[kind]);b.textContent=labels[kind];b.onclick=()=>{category=kind;selectedUpgrade=null;render()};rail.append(b)}
    $('labCategoryTitle').textContent=labels[category];$('labPaletteHint').textContent=mode==='script'?'Drag blocks into the stack. Order matters. Click to add at the selected join.':'Select a block to inspect its permanent unlock.';
    const palette=$('labPaletteBlocks');palette.innerHTML='';const paths={Survival:['vitality','constitution','ward','aegis','bastion','renewal','secondWind'],Mobility:['stride','dash','phaseDash','momentum'],Casting:['focus','precision','quickcast','efficiency','velocity','boltMaster','burstMaster','overcharge','specialist'],Mana:['reservoir','flow','harvest','killSurge'],Economy:['fortune','prosperity'],Scripting:['moreInk','grimoire']},options=category==='talent'?Object.entries(paths).flatMap(([path,ids])=>ids.map(id=>({...SS.talents.find(t=>t.id===id),path}))):SS.definitions[category];let lastPath='';
    for(const item of options){if(item.path&&item.path!==lastPath){const heading=document.createElement('h4');heading.className='upgrade-path-heading';heading.textContent=item.path+' path';palette.append(heading);lastPath=item.path}const owned=category==='talent'?SS.statsOwned?.(item.id):SS.owned(item.id),b=document.createElement('button');b.className='palette-block'+(owned?'':' locked');b.style.setProperty('--block-color',colors[category]);const ranked=category==='talent'&&SS.talentCap(item.id)>1,progress=ranked?`Rank ${SS.talentRank(item.id)}/${SS.talentCap(item.id)} · `:'',rankReq=SS.prerequisiteRanks?.[item.id],requires=rankReq?` · Requires ${SS.talents.find(t=>t.id===rankReq[0]).name} rank ${rankReq[1]}`:SS.prerequisites[item.id]?` · Requires ${SS.talents.find(t=>t.id===SS.prerequisites[item.id]).name}`:'';b.innerHTML=`<b>${item.name}</b><small>${item.detail}${requires} · ${progress}${owned?(ranked?'max rank':'unlocked'):`🔒 ${category==='talent'?SS.talentPrice(item.id):item.price} Magic`}</small>`;b.onpointerdown=e=>beginDrag(e,{source:'palette',id:item.id},b);b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(item.id)}};palette.append(b)}
    const root=$('labWorkContent');root.innerHTML='';if(mode==='script')renderScript(root);else renderUpgrade(root);
    $('labTip').textContent=SS.lastNote||'Connect blocks from top to bottom. Forms emit projectiles when reached.';
  }
  function renderScript(root){
    const head=document.createElement('div');head.className='lab-workspace-head';head.innerHTML=`<div><h3>Your spell script</h3><p>Rules affect forms below them. Control blocks affect the next form. Straight and Impact clear earlier rules.</p></div>`;
    const tabs=document.createElement('div');tabs.className='lab-loadouts';for(let i=0;i<3;i++){const b=document.createElement('button');b.className=i===SS.selected?'active':'';b.textContent=`Spell ${i+1}`;b.onclick=()=>{insertAt=null;SS.select(i)};tabs.append(b)}head.append(tabs);root.append(head);
    const tools=document.createElement('div');tools.className='spell-tools';for(const [label,action] of [['Undo',()=>SS.undo()],['Redo',()=>SS.redo()],['Export file',()=>{const blob=new Blob([SS.spellFile()],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`spellforge-spell-${SS.selected+1}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}],['Import file',()=>{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{if(input.files?.[0])SS.importFile(await input.files[0].text())};input.click()}],['Save blueprint',()=>{const name=window.prompt('Name this blueprint:');if(name)SS.saveBlueprint(name)}],['Blueprints',()=>{const list=SS.blueprints.map((b,i)=>`${i+1}. ${b.name}`).join('\n');const pick=window.prompt(`Saved blueprints:\n${list||'None yet'}\nEnter a number to load:`);if(pick)SS.loadBlueprint(Number(pick)-1)}],['Delete blueprint',()=>{const list=SS.blueprints.map((b,i)=>`${i+1}. ${b.name}`).join('\n');if(!list)return;const pick=window.prompt(`Delete which blueprint?\n${list}`),index=Number(pick)-1;if(pick&&Number.isInteger(index)&&index>=0&&index<SS.blueprints.length)SS.deleteBlueprint(index)}],['Duplicate group',()=>{if(rangeStart===null)return;const a=Math.min(rangeStart,Math.max(0,(insertAt??rangeStart+1)-1)),b=Math.max(rangeStart+1,insertAt??rangeStart+1);SS.duplicateRange(a,b,b);rangeStart=null;insertAt=null}],['Preview',()=>preview()]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;tools.append(b)}root.append(tools);
    const count=document.createElement('div'),cost=SS.estimateCost();count.className='script-count'+(cost>SS.stats().maxMana?' over-budget':'');count.textContent=`${SS.current().length} / ${SS.maxBlocks()} blocks · estimated ${cost} mana${cost>SS.stats().maxMana?' — full script exceeds mana capacity':''} · Shift-click a block, then a join to select a group`;root.append(count);
    const explanation=document.createElement('p');explanation.className='spell-explanation';explanation.textContent=explain(SS.current());root.append(explanation);
    const area=document.createElement('div');area.className='script-area';const script=document.createElement('div');script.className='script-stack';script.innerHTML='<div class="script-hat">When I cast this spell</div>';
    const current=SS.current();for(let i=0;i<=current.length;i++){
      const join=document.createElement('div');join.className='insert-zone'+(insertAt===i?' selected':'');join.dataset.insert=String(i);join.title='Drop a block here';join.onclick=()=>{insertAt=i;render()};script.append(join);
      if(i===current.length)break;
      const item=current[i],b=byId(item.id),node=document.createElement('div');node.className='script-block';node.dataset.scriptIndex=String(i);node.style.setProperty('--block-color',colors[b.kind]);if(rangeStart!==null&&insertAt!==null&&i>=Math.min(rangeStart,insertAt-1)&&i<Math.max(rangeStart+1,insertAt))node.classList.add('selected');node.innerHTML=`<span class="socket-tag">${labels[b.kind]}</span><strong>${b.name}</strong>`;window.SpellExpansion?.decorateBlock?.(node,item,b);
      const spec=SS.parameters[item.id];if(spec){const field=document.createElement('label');field.className='block-field';field.textContent=spec.label+' ';const input=document.createElement('input');input.type='number';input.min=String(spec.min);input.max=String(spec.max);input.step=String(spec.step);input.value=String(item.value??spec.default);input.onpointerdown=e=>e.stopPropagation();input.onclick=e=>e.stopPropagation();input.onchange=e=>SS.setParam(item.uid,e.target.value);field.append(input);node.append(field)}
      const grip=document.createElement('small');grip.textContent='⋮⋮';node.append(grip);node.onpointerdown=e=>{if(e.shiftKey){e.preventDefault();rangeStart=i;node.classList.add('selected');$('labTip').textContent='Click the join after the last block, then drag the selected group or duplicate it.';return}const from=Math.min(rangeStart??i,(insertAt??i+1)-1),to=Math.max((rangeStart??i)+1,insertAt??i+1),group=rangeStart!==null&&insertAt!==null&&i>=from&&i<to;beginDrag(e,group?{source:'range',from,to,id:item.id}:{source:'script',index:i,id:item.id},node)};script.append(node);
    }
    const tail=document.createElement('div');tail.className='script-tail';script.append(tail);area.append(script);
    const trash=document.createElement('div');trash.className='lab-trash';trash.dataset.trash='true';trash.innerHTML='↶<br>Drag a block here to remove it';area.append(trash);root.append(area);
  }
  function explain(script){const labels={bolt:'one bolt',fan:'three spreading shots',lance:'one piercing lance',nova:'a radial nova',scatter:'five close shots',orb:'one heavy orb',spiral:'four spiral shots',barrage:'five rapid shots',beam:'three parallel beams',arc:'an instant lightning arc',ring:'an expanding ring',mine:'a proximity mine'},forms=script.filter(x=>byId(x.id)?.kind==='shape').map(x=>labels[x.id]||byId(x.id).name),events=script.filter(x=>x.id.startsWith('on')).map(x=>byId(x.id).name),echo=script.find(x=>x.id==='echo'),repeat=script.find(x=>x.id==='repeatGroup');return forms.length?`Cast ${forms.join(', ')}${echo?`, then Echo after ${echo.value??.3}s`:''}${repeat?`; repeat a group ${repeat.value||2} times`:''}${events.length?`; ${events.join(', ')} fire attached forms`:''}.`:'Add a Form block to make this script cast.'}
  function preview(){clearInterval(previewTimer);const blocks=[...document.querySelectorAll('#labWorkContent [data-script-index]')],script=SS.current(),arena=window.SpellArena,origin=arena?.getGame().player,active=arena?.compile(script).filter(v=>v.event!=='cast'||arena.conditionsTrue(v,origin)),forms=new Set(active?.map(v=>v.uid)||[]),sequence=blocks.filter((_,i)=>byId(script[i].id)?.kind!=='shape'||forms.has(script[i].uid));let i=0;$('labTip').textContent='Tracing the connected script in slow motion…';previewTimer=setInterval(()=>{blocks.forEach(b=>b.classList.remove('executing'));if(i>=sequence.length){clearInterval(previewTimer);$('labTip').textContent='Trace complete. Event forms fire only when their trigger occurs in combat.';return}const block=sequence[i++],item=script[Number(block.dataset.scriptIndex)];block.classList.add('executing');$('labTip').textContent=`${i}/${sequence.length} · ${byId(item.id).name}${item.id.startsWith('on')?' waits for a trigger':''}`},450)}
  function renderUpgrade(root){
    const title=document.createElement('div');title.className='lab-workspace-head';title.innerHTML='<div><h3>Permanent unlocks</h3><p>Magic and purchases persist across runs. Drag a palette block here to inspect it.</p></div>';root.append(title);
    const zone=document.createElement('div');zone.className='unlock-zone';zone.dataset.unlock='true';root.append(zone);
    const item=byId(selectedUpgrade)||((category==='talent'?SS.talents:SS.definitions[category])[0]);if(!item)return;
    const isTalent=item.kind==='talent',owned=isTalent?SS.statsOwned?.(item.id):SS.owned(item.id);zone.style.setProperty('--block-color',colors[item.kind]);
    const ranked=isTalent&&SS.talentCap(item.id)>1,rank=ranked?SS.talentRank(item.id):0,cap=ranked?SS.talentCap(item.id):0,price=isTalent?SS.talentPrice(item.id):item.price;
    const current={vitality:`${SS.stats().maxHp} maximum health`,constitution:`${SS.stats().maxHp} maximum health`,renewal:`${SS.stats().waveHeal} health after each wave`,focus:`${Math.round(SS.stats().damage*100)}% spell damage`,reservoir:`${SS.stats().maxMana} maximum mana`,flow:`${Math.round(24*SS.stats().manaRegen)} mana per second`,fortune:`${Math.round((1+rank*.25)*100)}% Magic earned`}[item.id];
    const prerequisite=SS.prerequisites[item.id],rankReq=SS.prerequisiteRanks?.[item.id],required=rankReq&&SS.talentRank(rankReq[0])<rankReq[1]?SS.talents.find(t=>t.id===rankReq[0])?.name+' rank '+rankReq[1]:prerequisite&&!SS.talentRank(prerequisite)?SS.talents.find(t=>t.id===prerequisite)?.name:null;
    zone.innerHTML=`<div class="upgrade-preview-kind">${labels[item.kind]} block</div><div class="upgrade-preview-name">${item.name}</div><p>${item.detail}</p>${ranked?`<p>Rank ${rank} / ${cap} · ${current}</p>`:''}${required?`<p>Requires ${required} first.</p>`:''}<div class="upgrade-price">${owned?(ranked?'✓ Maximum rank':'✓ Permanently unlocked'):`${price} Magic`}</div>`;
    const buy=document.createElement('button');buy.className='upgrade-buy';buy.disabled=owned||!!required;buy.textContent=owned?(ranked?'Max rank':'Owned'):required?`Requires ${required}`:ranked?`Buy rank ${rank+1}`:`Unlock ${item.name}`;buy.onclick=()=>isTalent?SS.purchaseTalent(item.id):SS.purchaseBlock(item.id);zone.append(buy);
    if(owned&&!isTalent){const use=document.createElement('button');use.className='upgrade-buy use-block';use.textContent='Add to script';use.onclick=()=>{mode='script';SS.insertBlock(item.id,SS.current().length)};zone.append(use)}
    const hint=document.createElement('p');hint.className='upgrade-explain';hint.textContent=isTalent?'Talents take effect immediately and persist across runs.':'Once unlocked, this block can be placed in any spell script as often as you want.';root.append(hint);
  }
  function choose(id){const item=byId(id);if(!item)return;if(mode==='upgrades'){selectedUpgrade=id;render();return}if(!SS.owned(id)){selectedUpgrade=id;category=item.kind;mode='upgrades';render();return}SS.insertBlock(id,insertAt??SS.current().length);insertAt=null}
  function open(next='script'){mode=next;if(mode==='script'&&category==='talent')category='element';lab.classList.remove('hidden');SS.onEditorChange?.(true);render();$('closeLab').focus()}
  function close(){if(lab.classList.contains('hidden'))return;lab.classList.add('hidden');SS.onEditorChange?.(false)}
  function beginDrag(e,data,source){if(e.button!==undefined&&e.button!==0)return;e.preventDefault();drag={...data,x:e.clientX,y:e.clientY,sourceElement:source,ghost:null,target:null};$('labTip').textContent=data.source==='palette'?'Drop the block onto a join in the script.':'Drop onto a join to reorder, or into the return box.'}
  function targetAt(x,y){const item=document.elementFromPoint(x,y);return item?.closest?.('[data-insert],[data-trash],[data-unlock]')||null}
  function highlight(target){if(drag?.target&&drag.target!==target)drag.target.classList.remove('drop-ready');if(target)target.classList.add('drop-ready');if(drag)drag.target=target}
  document.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.ghost&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<6)return;if(!drag.ghost){drag.ghost=drag.sourceElement.cloneNode(true);drag.ghost.classList.add('drag-ghost');document.body.append(drag.ghost)}drag.ghost.style.left=e.clientX+14+'px';drag.ghost.style.top=e.clientY+14+'px';highlight(targetAt(e.clientX,e.clientY))});
  document.addEventListener('pointerup',e=>{if(!drag)return;const item=drag,target=targetAt(e.clientX,e.clientY),moved=Math.hypot(e.clientX-item.x,e.clientY-item.y)>6;item.target?.classList.remove('drop-ready');item.ghost?.remove();drag=null;
    if(!moved){if(item.source==='palette')choose(item.id);return}
    if(item.source==='palette'){
      if(target?.dataset?.insert!==undefined){if(SS.owned(item.id))SS.insertBlock(item.id,Number(target.dataset.insert));else choose(item.id)}
      else if(target?.dataset?.unlock!==undefined){mode='upgrades';selectedUpgrade=item.id;render()}
      else $('labTip').textContent='Drop onto a join between script blocks.';
    }else if(item.source==='range'){if(target?.dataset?.insert!==undefined)SS.moveRange(item.from,item.to,Number(target.dataset.insert));else if(target?.dataset?.trash!==undefined)SS.removeRange(item.from,item.to);rangeStart=null;insertAt=null}
    else if(target?.dataset?.insert!==undefined)SS.moveBlock(item.index,Number(target.dataset.insert));
    else if(target?.dataset?.trash!==undefined)SS.removeBlock(item.index);
  });
  document.addEventListener('pointercancel',()=>{drag?.target?.classList.remove('drop-ready');drag?.ghost?.remove();drag=null});
  $('labCodeTab').onclick=()=>{mode='script';if(category==='talent')category='element';render()};$('labUpgradeTab').onclick=()=>{mode='upgrades';render()};$('closeLab').onclick=close;
  lab.addEventListener('pointerdown',e=>{if(e.target===lab)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!lab.classList.contains('hidden')){e.preventDefault();close()}});
  SS.openEditor=open;SS.onRender=render;SS.onUnlockRequest=id=>{selectedUpgrade=id;category=byId(id).kind;mode='upgrades';if(lab.classList.contains('hidden'))open('upgrades');else render()};render();
})();
