(() => {
  const A=window.SpellArena,SS=window.SpellSystem,$=id=>document.getElementById(id),TAU=Math.PI*2;
  if(!A||!SS)return;
  const masteryKey='spellforge-mastery-v1';let mastery={};try{mastery=JSON.parse(localStorage.getItem(masteryKey)||'{}')||{}}catch{}
  const thresholds=[0,25,100,300,700],miniNames={furnacehound:'Furnace Hound',avalancheknight:'Avalanche Knight',stormchoir:'Storm Choir',sporemonarch:'Spore Monarch',gravityjailer:'Gravity Jailer'};
  const miniByRealm={ember:'furnacehound',frost:'avalancheknight',storm:'stormchoir',venom:'sporemonarch',radiant:'furnacehound',void:'gravityjailer',crystal:'avalancheknight',gravity:'gravityjailer'};
  const routeDefs={
    combat:{name:'Skirmish',icon:'⚔',detail:'Standard formation. Reliable Magic.',reward:1,population:1},
    elite:{name:'Elite Patrol',icon:'◆',detail:'More enemies and many more elite traits.',reward:1.65,population:1.18,elite:.28},
    forge:{name:'Wild Forge',icon:'✦',detail:'Mutate one Form in your active spell.',reward:1.15,population:1.05,forge:true},
    shrine:{name:'Quiet Shrine',icon:'✚',detail:'Restore health, mana, and a little shield.',reward:.9,population:.9,shrine:true},
    risk:{name:'Ruptured Chamber',icon:'☠',detail:'Severe rule. More than double rewards.',reward:2.25,population:1.3,risk:true}
  };
  const risks=[['Fractured Current','Mana regeneration falls to 45%; kills restore 7 mana.',{manaRegenMult:.45,manaStrain:true}],['Glass Floor','The floor erupts under you.',{glass:true}],['Crossfire','The arena fires hostile volleys.',{crossfire:true}],['Twin Hunt','Two minibosses enter this room.',{doubleMini:true}]];
  const mutationDefs={forked:['Forked','Adds two projectiles to Bolt, Fan, or Beam.'],hungry:['Hungry','Damage grows as this run gains kills.'],living:['Living Aim','Adds gentle steering velocity without replacing momentum.'],frozenBounce:['Rimebound','Bouncing shots leave slowing frost.'],volatile:['Volatile','Shots burst when their lifetime ends.'],unstableEcho:['Unstable Echo','Each cast repeats this Form once at reduced power.']};
  let panelPause=false,currentChoice=null;

  const card=document.createElement('section');card.className='card panel expansion-card';card.innerHTML='<div class="expansion-heading"><h2>Run Path</h2><button id="openTesting" title="Training tools">Test</button></div><div id="routeReadout" class="route-readout">Start a run to reveal its route.</div><div id="masteryReadout" class="mastery-readout"></div>';
  document.querySelector('.side')?.append(card);
  const overlay=document.createElement('div');overlay.id='expansionPanel';overlay.className='expansion-overlay hidden';overlay.innerHTML='<div class="expansion-window"><div class="expansion-head"><div><small id="expansionKicker">RUN MAP</small><h2 id="expansionTitle">Choose a route</h2></div><button id="closeExpansion">Close</button></div><div id="expansionContent"></div></div>';document.body.append(overlay);
  $('closeExpansion').onclick=()=>closePanel();overlay.addEventListener('pointerdown',e=>{if(e.target===overlay)closePanel()});
  let masteryDirty=0,masterySavePending=0;function persistMastery(){masterySavePending=0;try{localStorage.setItem(masteryKey,JSON.stringify(mastery));masteryDirty=0}catch{}}function saveMastery(force=false){if(force){persistMastery();return}if(masteryDirty<24||masterySavePending)return;const commit=()=>persistMastery();if(typeof requestIdleCallback==='function')masterySavePending=requestIdleCallback(commit,{timeout:1800})||1;else masterySavePending=setTimeout(commit,900)||1}
  function masteryLevel(id){const n=mastery[id]||0;let level=0;for(let i=1;i<thresholds.length;i++)if(n>=thresholds[i])level=i;return level}
  function decorateBlock(node,item,b){const level=masteryLevel(item.id);if(!level)return;node.classList.add(`mastery-${level}`);const badge=document.createElement('span');badge.className='mastery-badge';badge.textContent='★'.repeat(level);badge.title=`${b.name} mastery ${level} · ${mastery[item.id]} casts`;node.append(badge)}
  function refreshCard(game=A.getGame()){const route=game.route,top=Object.entries(mastery).sort((a,b)=>b[1]-a[1]).slice(0,3);$('routeReadout').innerHTML=route?`<b>${route.icon} ${route.name}</b><span>Reward ×${route.reward.toFixed(2)}${route.riskName?` · ${route.riskName}`:''}</span><div class="route-pips">${(game.routeHistory||[]).map(r=>`<i title="${r.name}">${r.icon}</i>`).join('')}</div>`:'Start a run to reveal its route.';$('masteryReadout').innerHTML=`<b>Spell mastery</b>${top.length?top.map(([id,n])=>`<span>${SS.block(id)?.name||id} · ${'★'.repeat(masteryLevel(id))||'learning'} <small>${n}</small></span>`).join(''):'<span>Cast blocks to master them.</span>'}`}
  function openPanel(title,html,kicker='RUN MAP',pause=true){const game=A.getGame();currentChoice=kicker;panelPause=pause&&game.phase==='playing';if(panelPause)game.phase='paused';$('expansionKicker').textContent=kicker;$('expansionTitle').textContent=title;$('expansionContent').innerHTML=html;overlay.classList.remove('hidden')}
  function closePanel(force=false){if(overlay.classList.contains('hidden'))return;if(!force&&currentChoice==='CHOOSE YOUR PATH')return;overlay.classList.add('hidden');const game=A.getGame();if(panelPause&&game.phase==='paused')game.phase='playing';panelPause=false;currentChoice=null}
  function started(game){game.route={...routeDefs.combat};game.routeHistory=[];game.spellMutations={};game.terrain=[];game.interactables=[];game.expansionClock=0;game.formationClock=2;game.miniSpawned=false;game.damageFeed=[];game.trainingTools={scale:1,hitboxes:false,numbers:true};createInteractables(game);refreshCard(game)}
  function createInteractables(game){const realm=window.RealmSystem?.current()?.id||'ember',kinds={ember:'oil',frost:'iceCrystal',storm:'conduit',venom:'pod',radiant:'mirror',void:'rift',crystal:'prism',gravity:'anchor'};game.interactables=[{x:120,y:105,r:24,hp:3,kind:kinds[realm]},{x:840,y:495,r:24,hp:3,kind:kinds[realm]}]}
  function routeOptions(wave){const sequence=[['combat','elite','forge'],['risk','shrine','elite'],['forge','risk','combat'],['elite','shrine','risk']],ids=sequence[Math.floor(wave/3)%sequence.length];return ids.slice(0,2)}
  function waveStarted(game){game.miniSpawned=false;game.formationClock=1.8;game.formationPlan=formationFor();createInteractables(game);if(game.mode==='training'||game.mode==='bossrush'||game.wave<=1||game.wave%3!==1){refreshCard(game);return}const options=routeOptions(game.wave);openPanel(`Wave ${game.wave} · choose a chamber`,`<p class="route-copy">The route changes this wave's enemies, rewards, and arena rules.</p><div class="route-grid">${options.map(id=>{const r=routeDefs[id];return`<button data-route="${id}"><span>${r.icon}</span><strong>${r.name}</strong><small>${r.detail}</small><em>Magic ×${r.reward.toFixed(2)}</em></button>`}).join('')}</div><div class="path-line">${game.routeHistory.map(r=>`<span>${r.icon}</span>`).join('<i>›</i>')}<i>›</i><b>?</b></div>`,'CHOOSE YOUR PATH');$('closeExpansion').style.visibility='hidden';overlay.querySelectorAll('[data-route]').forEach(button=>button.onclick=()=>chooseRoute(button.dataset.route,game))}
  function chooseRoute(id,game){const chosen={...routeDefs[id]};if(chosen.risk){const [name,detail,effect]=risks[(game.wave+game.routeHistory.length)%risks.length];Object.assign(chosen,effect,{riskName:name,detail:`${detail} ${chosen.detail}`})}game.route=chosen;game.routeHistory.push({name:chosen.name,icon:chosen.icon});if(chosen.shrine){game.player.hp=Math.min(game.stats.maxHp,game.player.hp+45);game.player.mana=game.stats.maxMana;A.grantShield(18)}$('closeExpansion').style.visibility='';closePanel(true);if(chosen.forge)setTimeout(()=>offerMutation(game),50);A.say(`${chosen.name}${chosen.riskName?` · ${chosen.riskName}`:''}`,2.5);refreshCard(game)}
  function wavePopulation(game){return game.route?.population||1}
  function formationFor(){const realm=window.RealmSystem?.current()?.id||'ember';return({ember:'wedge',frost:'phalanx',storm:'battery',venom:'brood',radiant:'crossfire',void:'encirclement',crystal:'phalanx',gravity:'orbit'})[realm]}
  function chooseSpawnType(base,game){if(game.wave%5===0||game.mode==='training'||game.mode==='bossrush')return base;const mini=miniByRealm[window.RealmSystem?.current()?.id||'ember'];const due=game.wave>=3&&(game.wave-3)%5===0;if(due&&!game.miniSpawned){game.miniSpawned=true;return mini}if(game.route?.doubleMini&&game.spawned<2)return mini;return base}
  function enemySpawned(e,game){e.formationRole=game.spawned%3;e.expansionAttack=2+Math.random()*2;if(A.bossTypes.includes(e.type)){e.ward=Math.max(e.ward||0,1.2);game.bossIntro={name:bossName(e.type),type:e.type,life:2.3,max:2.3};game.finisher=null}if(A.minibossTypes.includes(e.type)){e.special=1.8;const checkpoint=Math.max(5,Math.ceil(game.wave/5)*5),realmBoss=window.RealmSystem?.current()?.boss||'engine',nextBoss=window.RealmSystem?.boss?.(checkpoint,realmBoss)||realmBoss,bossMax=A.bossHealth?.(nextBoss,checkpoint)||Math.max(1600,e.max*5);e.max=e.hp=Math.round(bossMax*.5);A.say(`${miniNames[e.type]} blocks the route!`,2.3)}}
  function bossName(type){return({engine:'Twelvefold Engine',mirror:'Counterforge',voidboss:'Void Sovereign',frostboss:'Glacial Architect',splitboss:'Twin Crucible',tempestboss:'Tempest Crown',broodboss:'Brood Cathedral',sunboss:'Solar Regent',prismboss:'Prism Warden'})[type]||type}
  function offerMutation(game){const forms=SS.current().filter(x=>SS.block(x.id)?.kind==='shape');if(!forms.length)return;const form=forms.sort((a,b)=>masteryLevel(b.id)-masteryLevel(a.id))[0],existing=game.spellMutations[form.uid]||[],stack=Array.isArray(existing)?existing:[existing],choices=Object.keys(mutationDefs).sort(()=>Math.random()-.5).slice(0,3),current=stack.length?` Current: ${stack.map(id=>mutationDefs[id]?.[0]||id).join(' + ')}.`:'';openPanel('Mutate a spell Form',`<p class="route-copy">Mutating <strong>${SS.block(form.id).name}</strong>. Every choice stacks on this Form.${current}</p><div class="mutation-choice">${choices.map(id=>{const rank=stack.filter(v=>v===id).length;return`<button data-spell-mutation="${id}"><strong>${mutationDefs[id][0]}${rank?` · rank ${rank+1}`:''}</strong><small>${mutationDefs[id][1]}</small></button>`}).join('')}</div>`,'WILD FORGE');overlay.querySelectorAll('[data-spell-mutation]').forEach(b=>b.onclick=()=>{const id=b.dataset.spellMutation,list=game.spellMutations[form.uid]??[];game.spellMutations[form.uid]=Array.isArray(list)?[...list,id]:[list,id];const rank=game.spellMutations[form.uid].filter(v=>v===id).length;$('closeExpansion').style.visibility='';closePanel(true);A.say(`${SS.block(form.id).name} gained ${mutationDefs[id][0]}${rank>1?` ×${rank}`:''}!`,2.4);refreshCard(game)})}
  function mutationFor(uid){const value=A.getGame().spellMutations?.[uid]||[];return Array.isArray(value)?value:[value]}
  function cast(active,game){for(const id of new Set(SS.current().map(item=>item.id)))mastery[id]=(mastery[id]||0)+1;masteryDirty++;saveMastery();const elements=new Set(active.flatMap(v=>v.elements)),p=game.player;let terrain=null;if(elements.has('ember')&&elements.has('frost'))terrain={kind:'steam',x:p.x,y:p.y,r:120,life:5};else if(elements.has('storm')&&elements.has('frost'))terrain={kind:'chargedWater',x:p.x,y:p.y,r:105,life:5};else if(elements.has('void')&&elements.has('radiant'))terrain={kind:'implosion',x:p.x,y:p.y,r:145,life:4};else if(elements.has('venom')&&elements.has('ember'))terrain={kind:'toxicFlame',x:p.x,y:p.y,r:115,life:4};else if(elements.has('gravity')&&elements.has('crystal'))terrain={kind:'shardWell',x:p.x,y:p.y,r:135,life:4};if(terrain){terrain.tick=0;const existing=game.terrain.find(z=>z.kind===terrain.kind&&Math.hypot(z.x-terrain.x,z.y-terrain.y)<140);if(existing){existing.life=Math.max(existing.life,terrain.life);existing.x=(existing.x+terrain.x)/2;existing.y=(existing.y+terrain.y)/2}else{game.terrain.push(terrain);if(game.terrain.length>6)game.terrain.splice(0,game.terrain.length-6);A.say(`${({steam:'Steam Veil',chargedWater:'Storm Pool',implosion:'Eclipse Well',toxicFlame:'Blightfire',shardWell:'Shard Singularity'})[terrain.kind]} reaction!`,1.4)}}for(const v of active){const echoes=v.mutations?.filter(id=>id==='unstableEcho').length||(v.mutation==='unstableEcho'?1:0);for(let i=0;i<echoes;i++)setTimeout(()=>{const g=A.getGame();if(g.phase==='playing')A.shot(v,Math.atan2(300-g.player.y,780-g.player.x),g.player,0,.45*Math.pow(.78,i),++g.nextCastId)},220*(i+1))}triggerInteractables(elements,game)}
  function triggerInteractables(elements,game){for(const o of game.interactables||[]){if(o.dead||Math.hypot(o.x-game.player.x,o.y-game.player.y)>260)continue;const works=(o.kind==='oil'&&elements.has('ember'))||(o.kind==='iceCrystal'&&elements.has('ember'))||(o.kind==='conduit'&&elements.has('storm'))||(o.kind==='pod'&&elements.has('venom'))||(o.kind==='mirror'&&elements.has('radiant'))||(o.kind==='rift'&&elements.has('void'))||(o.kind==='prism'&&elements.has('crystal'))||(o.kind==='anchor'&&elements.has('gravity'));if(!works)continue;o.dead=true;game.blasts.push({x:o.x,y:o.y,radius:110,life:.5,max:.5,col:'#fff0a2'});for(const e of game.enemies)if(Math.hypot(e.x-o.x,e.y-o.y)<125)e.hp-=Math.max(25,e.max*.12);A.particles(o.x,o.y,'#fff0a2',28,'shard',1.2)}}
  function enemyDefeated(e,game){if(game.route?.manaStrain)game.player.mana=Math.min(game.stats.maxMana,game.player.mana+7);if(A.minibossTypes.includes(e.type)){SS.addMagic(Math.round(90+game.wave*14),'miniboss defeated');A.grantShield(12);if(Math.random()<.7)setTimeout(()=>offerMutation(game),80)}if(A.bossTypes.includes(e.type)){game.finisher={x:e.x,y:e.y,life:1.4,max:1.4,name:bossName(e.type)};for(let i=0;i<4;i++)setTimeout(()=>A.particles(e.x,e.y,['#fff0a2','#d9afff','#85def0'][i%3],22,'ring',1.4),i*90)}}
  function damageNumber(e,amount){const game=A.getGame();if(game.mode!=='training'||!game.trainingTools?.numbers)return;game.damageFeed??=[];game.damageFeed.push({x:e.x,y:e.y-10,n:Math.round(amount),life:.7,max:.7})}
  function update(dt,game){for(const n of game.damageFeed||[]){n.life-=dt;n.y-=dt*24}game.damageFeed=(game.damageFeed||[]).filter(n=>n.life>0);game.expansionClock=(game.expansionClock||0)+dt;if(game.bossIntro)game.bossIntro.life-=dt;if(game.bossInitializing)return;if(game.finisher)game.finisher.life-=dt;for(const z of game.terrain||[]){z.life-=dt;z.tick-=dt;if(z.tick<=0){z.tick=.32;for(const e of game.enemies){const d=Math.hypot(e.x-z.x,e.y-z.y);if(d>z.r)continue;if(z.kind==='steam')e.attack+=.12;if(z.kind==='chargedWater'){e.hp-=6;e.slow=Math.max(e.slow,.5)}if(z.kind==='implosion'){e.x+=(z.x-e.x)*.08;e.y+=(z.y-e.y)*.08;e.hp-=3}if(z.kind==='toxicFlame'){e.hp-=9;e.burn=Math.max(e.burn,1)}if(z.kind==='shardWell'){e.hp-=7;e.slow=Math.max(e.slow,.3)}}}}game.terrain=(game.terrain||[]).filter(z=>z.life>0);updateRisk(dt,game);updateFormations(dt,game);updateMinibosses(dt,game);if(game.mode==='training')sampleDps(dt,game)}
  function updateRisk(dt,game){game.riskClock=(game.riskClock||1)-dt;if(game.riskClock>0)return;game.riskClock=game.route?.glass?1.25:game.route?.crossfire?1.7:99;if(game.route?.glass)A.bossHazard('collapse',game.player.x,game.player.y,54,1.5,.75);if(game.route?.crossfire){const fake={x:20,y:80+Math.random()*440,type:'crossfire',animAttack:0};A.enemyShot(fake,0,390);const other={x:940,y:80+Math.random()*440,type:'crossfire',animAttack:0};A.enemyShot(other,Math.PI,390)}}
  function updateFormations(dt,game){
    game.formationClock-=dt;if(game.formationClock>0)return;game.formationClock=3.2;
    const alive=game.enemies.filter(e=>!A.bossTypes.includes(e.type)&&!A.minibossTypes.includes(e.type));if(alive.length<2)return;
    const plan=game.formationPlan;
    if(plan==='phalanx'){
      for(const e of alive.filter(e=>e.type==='shieldbearer'||e.type==='tank'))for(const ally of alive)if(Math.hypot(e.x-ally.x,e.y-ally.y)<145)ally.ward=Math.max(ally.ward,.7);
    }else if(plan==='battery'){
      for(const e of alive.filter(e=>['shooter','sniper','thunderhead','vectorscribe'].includes(e.type)).slice(0,4))A.enemyShot(e,Math.atan2(game.player.y-e.y,game.player.x-e.x),340);
    }else if(plan==='encirclement'||plan==='orbit'){
      for(const [i,e] of alive.slice(0,5).entries()){const a=game.expansionClock+i*TAU/5;e.x=Math.max(e.r,Math.min(960-e.r,game.player.x+Math.cos(a)*220));e.y=Math.max(e.r,Math.min(600-e.r,game.player.y+Math.sin(a)*180))}
    }else if(plan==='brood'){
      for(const e of alive.filter(e=>e.type==='healer'))for(const ally of alive)if(Math.hypot(e.x-ally.x,e.y-ally.y)<170)ally.hp=Math.min(ally.max,ally.hp+ally.max*.08);
    }else if(plan==='crossfire'){
      for(const e of alive.slice(0,3))A.enemyShot(e,Math.atan2(game.player.y-e.y,game.player.x-e.x),310);
    }
  }  function updateMinibosses(dt,game){for(const e of game.enemies.filter(e=>A.minibossTypes.includes(e.type)&&e.hp>0)){e.special-=dt;if(e.special>0)continue;e.special=e.hp<e.max*.5?2.2:3.3;const p=game.player,a=Math.atan2(p.y-e.y,p.x-e.x);if(e.type==='furnacehound'){for(let i=-1;i<=1;i++)A.elementalOrb(e,a+i*.22,'ember',300,12);A.bossHazard('inferno',e.x,e.y,65,3,.5)}if(e.type==='avalancheknight'){A.bossHazard('ice',p.x,p.y,105,4,.7);for(let i=-2;i<=2;i++)A.elementalOrb(e,a+i*.14,'frost',270,9)}if(e.type==='stormchoir'){for(let i=0;i<3;i++)A.bossHazard('lightning',p.x+Math.cos(i*TAU/3)*85,p.y+Math.sin(i*TAU/3)*85,30,1.4,.75)}if(e.type==='sporemonarch'){A.bossHazard('spore',p.x,p.y,95,4,.8);e.hp=Math.min(e.max,e.hp+e.max*.06)}if(e.type==='gravityjailer'){A.bossHazard('gravity',p.x,p.y,125,3,.7);for(let i=0;i<5;i++)A.elementalOrb(e,a+i*TAU/5,'gravity',220,9)}}}
  function sampleDps(dt,game){game.dpsClock=(game.dpsClock||0)+dt;if(game.dpsClock<.5)return;game.dpsClock=0;game.dpsSamples??=[];game.dpsSamples.push({t:game.trainingTime||0,d:(game.trainingDamage||0)/Math.max(1,game.trainingTime||1)});if(game.dpsSamples.length>40)game.dpsSamples.shift();drawDpsCanvas(game)}
  function draw(g,game){for(const z of game.terrain||[]){const hue={steam:'#d8eef0',chargedWater:'#8fdcff',implosion:'#b476ff',toxicFlame:'#a8ed67',shardWell:'#7ff7df'}[z.kind];g.save();g.globalAlpha=.22+.08*Math.sin(game.expansionClock*6);g.fillStyle=hue;g.strokeStyle=hue;g.lineWidth=3;g.beginPath();g.arc(z.x,z.y,z.r,0,TAU);g.fill();g.setLineDash([8,8]);g.stroke();g.restore()}for(const o of game.interactables||[]){if(o.dead)continue;const hue={oil:'#ff9b48',iceCrystal:'#85def0',conduit:'#d9afff',pod:'#90df82',mirror:'#fff0a2',rift:'#b795ff',prism:'#8cf1e9',anchor:'#a6a4ff'}[o.kind];g.save();g.translate(o.x,o.y);g.fillStyle=hue+'88';g.strokeStyle=hue;g.lineWidth=3;g.rotate(game.expansionClock*.25);g.fillRect(-o.r,-o.r,o.r*2,o.r*2);g.strokeRect(-o.r,-o.r,o.r*2,o.r*2);g.restore()}drawFormation(g,game);for(const n of game.damageFeed||[]){g.save();g.globalAlpha=n.life/n.max;g.fillStyle='#fff0a2';g.font='bold 15px system-ui';g.textAlign='center';g.fillText(n.n,n.x,n.y);g.restore()}if(game.trainingTools?.hitboxes){g.save();g.strokeStyle='#55ff9aaa';g.setLineDash([4,3]);g.beginPath();g.arc(game.player.x,game.player.y,game.player.r,0,TAU);g.stroke();for(const e of game.enemies){g.beginPath();g.arc(e.x,e.y,e.r,0,TAU);g.stroke()}g.restore()}if(game.bossIntro?.life>0)drawBossIntro(g,game.bossIntro);if(game.finisher?.life>0)drawFinisher(g,game.finisher)}
  function drawFormation(g,game){const grouped=new Map();for(const e of game.enemies){if(A.bossTypes.includes(e.type))continue;const list=grouped.get(e.squad)||[];list.push(e);grouped.set(e.squad,list)}g.save();g.strokeStyle='#f6d18438';g.lineWidth=2;g.setLineDash([6,8]);for(const list of grouped.values())if(list.length>1){g.beginPath();list.forEach((e,i)=>i?g.lineTo(e.x,e.y):g.moveTo(e.x,e.y));g.stroke()}g.restore()}
  function drawBossIntro(g,intro){const t=intro.life/intro.max;g.save();g.globalAlpha=Math.min(1,(1-t)*4,t*4);g.fillStyle='#080b12dd';g.fillRect(0,0,960,78);g.fillRect(0,540,960,60);g.textAlign='center';g.fillStyle='#e8c47f';g.font='700 12px system-ui';g.fillText('BOSS ENGAGED',480,24);g.fillStyle='#fff1d2';g.font='30px Georgia';g.fillText(intro.name,480,57);g.restore()}
  function drawFinisher(g,f){const progress=1-f.life/f.max;g.save();g.strokeStyle='#fff0a2';g.lineWidth=7*(1-progress);g.globalAlpha=1-progress;for(let i=0;i<4;i++){g.beginPath();g.arc(f.x,f.y,30+progress*(90+i*42),0,TAU);g.stroke()}g.textAlign='center';g.fillStyle='#fff4d5';g.font='bold 25px system-ui';g.fillText(`${f.name} shattered`,480,110);g.restore()}
  function timeScale(game){return game.mode==='training'?(game.trainingTools?.scale||1):1}
  function openTesting(){const game=A.getGame();openPanel('Arcane testing console',`<div class="testing-grid"><label>Time scale <select id="testScale"><option value=".25">0.25×</option><option value=".5">0.5×</option><option value="1">1×</option></select></label><label><input id="testHitboxes" type="checkbox"> Show hitboxes</label><label><input id="testNumbers" type="checkbox"> Damage numbers</label><button data-test="mana">Refill mana</button><button data-test="clear">Clear entities</button><button data-test="group">Spawn enemy group</button><button data-test="mini">Spawn miniboss</button><button data-test="boss">Spawn boss at phase two</button></div><canvas id="dpsGraph" width="620" height="170"></canvas><p class="route-copy">The graph records training room DPS every half second. Boss phase testing uses this realm's boss.</p>`,'SPELL DEBUGGER',false);$('testScale').value=String(game.trainingTools?.scale||1);$('testScale').onchange=e=>{game.trainingTools??={};game.trainingTools.scale=Number(e.target.value)};$('testHitboxes').checked=!!game.trainingTools?.hitboxes;$('testHitboxes').onchange=e=>game.trainingTools.hitboxes=e.target.checked;overlay.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>testAction(b.dataset.test,game));drawDpsCanvas(game)}
  function testAction(action,game){if(action==='mana')game.player.mana=game.stats.maxMana;if(action==='clear'){game.enemies=[];game.hostile=[];game.shots=[]}if(action==='group')for(let i=0;i<6;i++)game.enemies.push(A.makeEnemy(['chaser','shooter','tank'][i%3],600+Math.cos(i*TAU/6)*130,300+Math.sin(i*TAU/6)*130));if(action==='mini'){const type=miniByRealm[window.RealmSystem?.current()?.id||'ember'],e=A.makeEnemy(type,690,300);game.enemies.push(e);enemySpawned(e,game)}if(action==='boss'){const type=window.RealmSystem?.current()?.boss||'engine',e=A.makeEnemy(type,700,300);e.hp=e.max*.49;e.phase2=false;game.enemies.push(e);enemySpawned(e,game)}A.say(`Test: ${action}`,1)}
  function drawDpsCanvas(game){const c=$('dpsGraph');if(!c)return;const g=c.getContext('2d'),data=game.dpsSamples||[];g.fillStyle='#101827';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#263954';for(let y=25;y<c.height;y+=35){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}const max=Math.max(10,...data.map(x=>x.d));g.strokeStyle='#e6bd72';g.lineWidth=3;g.beginPath();data.forEach((x,i)=>{const px=i/Math.max(1,data.length-1)*(c.width-30)+15,py=c.height-18-x.d/max*(c.height-38);i?g.lineTo(px,py):g.moveTo(px,py)});g.stroke();g.fillStyle='#dce8f3';g.font='13px system-ui';g.fillText(`Peak ${Math.round(max)} DPS`,12,18)}
  $('openTesting').onclick=openTesting;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.classList.contains('hidden')&&currentChoice!=='CHOOSE YOUR PATH')closePanel()});
  window.SpellExpansion={started,waveStarted,wavePopulation,chooseSpawnType,enemySpawned,enemyDefeated,cast,damageNumber,update,draw,timeScale,mutationFor,masteryLevel,decorateBlock,offerMutation,openTesting,routeDefs,miniNames};refreshCard();
  window.addEventListener?.('beforeunload',()=>saveMastery(true));
})();
