(() => {
  const SS=window.SpellSystem,A=window.SpellArena,$=id=>document.getElementById(id);
  const settingsKey='spellforge-settings-v1',achievementKey='spellforge-achievements-v1';
  let stored={};try{stored=JSON.parse(localStorage.getItem(settingsKey)||'{}')||{}}catch{}
  const settings={volume:stored.volume??1,musicVolume:stored.musicVolume??.75,effectsVolume:stored.effectsVolume??1,shake:stored.shake??.6,lowEffects:!!stored.lowEffects,reducedFlash:!!stored.reducedFlash,arena:stored.arena||'classic'};
  const bindings={w:'w',a:'a',s:'s',d:'d',shift:'shift',p:'p',cast:' ',...(stored.bindings||{})};
  window.SpellAudio.volume=settings.volume;window.SpellAudio.musicVolume=settings.musicVolume;window.SpellAudio.effectsVolume=settings.effectsVolume;
  let achievements={};try{achievements=JSON.parse(localStorage.getItem(achievementKey)||'{}')||{}}catch{}
  const save=()=>{try{localStorage.setItem(settingsKey,JSON.stringify({...settings,bindings}))}catch{}};
  const persistAchievements=()=>{try{localStorage.setItem(achievementKey,JSON.stringify(achievements))}catch{}};
  const card=document.createElement('section');card.className='card panel feature-card';
  card.innerHTML='<h2>Run & Training</h2><p class="muted" id="wavePreview">Choose a mode, then enter the arena.</p><div class="mode-grid"><button data-mode="normal">Endless</button><button data-mode="training">Training room</button><button data-mode="bossrush">Boss Rush</button><button data-mode="noheal">No healing</button><button data-mode="oneslot">One spell slot</button></div><label class="feature-label">Arena <select id="arenaChoice"><option value="classic">Classic</option><option value="crossroads">Crossroads</option><option value="gauntlet">Gauntlet</option></select></label><label class="feature-label">Training target <select id="trainingTarget"></select></label><div id="trainingReadout" class="feature-readout"></div><button id="openSettings" class="feature-settings">Settings & progress</button>';
  document.querySelector('.side').append(card);
  const targetSelect=$('trainingTarget');for(const entry of window.EnemyJournal.entries.filter(e=>!e.boss)){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.name;targetSelect.append(option)}const dummyOption=document.createElement('option');dummyOption.value='dummy';dummyOption.textContent='Practice dummy';targetSelect.prepend(dummyOption);targetSelect.value='dummy';
  $('arenaChoice').value=settings.arena;$('arenaChoice').onchange=e=>{settings.arena=e.target.value;save()};
  card.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>A.start(button.dataset.mode));
  targetSelect.onchange=()=>{const game=A.getGame();if(game.mode!=='training')return;const enemy=A.makeEnemy(targetSelect.value,670,300);if(targetSelect.value==='dummy')enemy.hp=enemy.max=100000;else{enemy.attack=999;enemy.speed=0}game.enemies=[enemy];game.trainingDamage=game.trainingCasts=game.trainingMana=game.trainingTime=0};
  const panel=document.createElement('div');panel.id='featurePanel';panel.className='feature-overlay hidden';panel.innerHTML='<div class="feature-window"><div class="feature-head"><h2 id="featureTitle">Settings</h2><button id="closeFeature">Done</button></div><div id="featureContent"></div></div>';document.body.append(panel);$('closeFeature').onclick=closePanel;panel.addEventListener('pointerdown',e=>{if(e.target===panel)closePanel()});
  let panelPause=false,panelKind='';
  function openPanel(title,html,kind='settings'){panelKind=kind;$('featureTitle').textContent=title;$('featureContent').innerHTML=html;panel.classList.remove('hidden');const game=A.getGame();if(game.phase==='playing'){game.phase='paused';panelPause=true}}
  function closePanel(force=false){if(panel.classList.contains('hidden')||(panelKind==='reward'&&!force))return;panel.classList.add('hidden');const game=A.getGame();if(panelPause&&game.phase==='paused')game.phase='playing';panelPause=false;panelKind=''}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.classList.contains('hidden')&&panelKind!=='reward'){e.preventDefault();closePanel()}});
  function settingsPanel(){const unlocked=Object.values(SS.definitions).flat().filter(b=>SS.owned(b.id)).length,total=Object.values(SS.definitions).flat().length;openPanel('Settings & progress',`<div class="feature-grid"><label>Master volume <input id="featureVolume" type="range" min="0" max="1" step=".05" value="${settings.volume}"></label><label>Music volume <input id="musicVolume" type="range" min="0" max="1" step=".05" value="${settings.musicVolume}"></label><label>Effects volume <input id="effectsVolume" type="range" min="0" max="1" step=".05" value="${settings.effectsVolume}"></label><label>Screen shake <input id="featureShake" type="range" min="0" max="1" step=".1" value="${settings.shake}"></label><label><input id="featureEffects" type="checkbox" ${settings.lowEffects?'checked':''}> Extra-low effects mode</label><label><input id="featureFlashes" type="checkbox" ${settings.reducedFlash?'checked':''}> Reduce flashes</label></div><h3>Controls</h3><div class="binding-grid">${Object.entries(bindings).map(([action,key])=>`<button data-bind="${action}">${action.toUpperCase()}: ${key===' '?'SPACE':key.toUpperCase()}</button>`).join('')}</div><p class="muted">Click a key, then press its replacement. Gamepad sticks and touch controls work automatically.</p><h3>Permanent progress</h3><p>${unlocked} / ${total} spell blocks available · ${SS.talents.filter(t=>SS.talentRank(t.id)>0).length} talents purchased · ${Object.keys(achievements).length} boss achievements.</p><p>Health ${SS.stats().maxHp} · Mana ${SS.stats().maxMana} · Regen ${Math.round(24*SS.stats().manaRegen)}/s · Damage ×${SS.stats().damage.toFixed(2)} · Dash ${SS.stats().dashCooldown.toFixed(1)}s</p><p class="muted">Boss achievements can permanently grant blocks. Upgrade purchases and journal discoveries remain saved.</p>`);$('featureVolume').oninput=e=>{settings.volume=Number(e.target.value);window.SpellAudio.volume=settings.volume;save()};$('musicVolume').oninput=e=>{settings.musicVolume=Number(e.target.value);window.SpellAudio.musicVolume=settings.musicVolume;save()};$('effectsVolume').oninput=e=>{settings.effectsVolume=Number(e.target.value);window.SpellAudio.effectsVolume=settings.effectsVolume;save()};$('featureShake').oninput=e=>{settings.shake=Number(e.target.value);save()};$('featureEffects').onchange=e=>{settings.lowEffects=e.target.checked;save()};$('featureFlashes').onchange=e=>{settings.reducedFlash=e.target.checked;save()};$('featureContent').querySelectorAll('[data-bind]').forEach(button=>button.onclick=()=>{button.textContent='Press a key…';button.onkeydown=e=>{e.preventDefault();e.stopPropagation();const key=e.key.toLowerCase();if(Object.values(bindings).includes(key)){button.textContent='Already in use';return}bindings[button.dataset.bind]=key;save();button.textContent=`${button.dataset.bind.toUpperCase()}: ${key.toUpperCase()}`;button.onkeydown=null};button.focus()})}
  $('openSettings').onclick=settingsPanel;
  const touch=document.createElement('div');touch.className='touch-controls';touch.setAttribute('aria-label','Mobile game controls');
  touch.innerHTML='<div class="touch-stick move-stick" data-stick="move"><div class="stick-ring"><i></i></div><b>MOVE</b></div><button class="touch-dash" data-mobile="dash">DASH</button><div class="touch-aim-hint">TAP OR DRAG TO SHOOT</div>';
  const stage=$('arena').parentElement;stage.append(touch);
  const heldMove={w:false,a:false,s:false,d:false};
  function setMove(x,y){const next={a:x<-.28,d:x>.28,w:y<-.28,s:y>.28};for(const key of Object.keys(next))if(next[key]!==heldMove[key]){heldMove[key]=next[key];A.setKey(key,next[key])}}
  function bindStick(stick,kind){const ring=stick.querySelector('.stick-ring'),knob=ring.querySelector('i');let pointer=null;
    function update(e){const box=ring.getBoundingClientRect(),cx=box.left+box.width/2,cy=box.top+box.height/2,max=box.width*.34;let x=e.clientX-cx,y=e.clientY-cy,len=Math.hypot(x,y);if(len>max){x=x/len*max;y=y/len*max;len=max}knob.style.transform=`translate(${x}px,${y}px)`;const nx=x/max,ny=y/max;if(kind==='move')setMove(nx,ny);else{const p=A.getGame().player;if(len>max*.18){A.setAim(p.x+nx*430,p.y+ny*430);A.setCasting(true)}else A.setCasting(false)}}
    function release(e){if(pointer!==null&&e?.pointerId!==undefined&&e.pointerId!==pointer)return;pointer=null;knob.style.transform='translate(0,0)';if(kind==='move')setMove(0,0);else A.setCasting(false)}
    stick.onpointerdown=e=>{e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);update(e)};stick.onpointermove=e=>{if(e.pointerId===pointer)update(e)};stick.onpointerup=stick.onpointercancel=release;stick.onlostpointercapture=release
  }
  touch.querySelectorAll('[data-stick]').forEach(stick=>bindStick(stick,stick.dataset.stick));
  const spellButtons=[],dashButton=touch.querySelector('[data-mobile="dash"]');if(dashButton)dashButton.onpointerdown=e=>{e.preventDefault();A.dash()};
  const layouts={classic:[{x:280,y:170,r:43},{x:660,y:420,r:49},{x:490,y:300,r:34}],crossroads:[{x:270,y:170,r:42},{x:690,y:170,r:42},{x:270,y:430,r:42},{x:690,y:430,r:42}],gauntlet:[{x:360,y:130,r:35},{x:600,y:130,r:35},{x:360,y:470,r:35},{x:600,y:470,r:35},{x:480,y:300,r:42}]};
  const realmLayouts=[layouts.classic,[{x:240,y:150,r:38},{x:480,y:300,r:48},{x:720,y:450,r:38}],[{x:290,y:300,r:34},{x:480,y:145,r:38},{x:670,y:300,r:34},{x:480,y:455,r:38}],layouts.crossroads,[{x:220,y:300,r:46},{x:480,y:170,r:34},{x:740,y:300,r:46},{x:480,y:430,r:34}],[{x:340,y:180,r:42},{x:620,y:420,r:42}],[{x:250,y:130,r:34},{x:480,y:300,r:58},{x:710,y:470,r:34}],layouts.gauntlet];
  function started(game,rocks){const realmIndex=window.RealmSystem?.state.active??0,chosen=settings.arena==='classic'?(realmLayouts[realmIndex]||layouts.classic):(layouts[settings.arena]||layouts.classic);rocks.splice(0,rocks.length,...chosen.map(r=>({...r,hp:110,maxHp:110})));game.pickups=[];game.hazards=[];game.trails=[];game.replay=[];game.replayClock=0;game.trainingUiClock=0;game.trainingTime=0;game.trainingDamage=0;game.trainingCasts=0;game.trainingMana=0;game.mutations=[];game.milestones=new Set();game.waveEvent='';$('trainingReadout').textContent=game.mode==='training'?'Aim and cast to measure damage.':''}
  function waveStarted(game){
    if(game.mode==='training')return;
    if(game.eventRegenBoost){game.stats.manaRegen/=game.eventRegenBoost;game.eventRegenBoost=0}
    const realm=window.RealmSystem?.current(),next=game.wave+(game.mode==='bossrush'?5:1),formation=['mixed','swarm','ranged','armored'][next%4],enemyNames=(realm?.enemies||[]).map(id=>window.EnemyJournal?.entries.find(e=>e.id===id)?.name||id).slice(0,3).join(', '),boss=next%5===0?' · BOSS':'';
    $('wavePreview').textContent=`${realm?.name||'Arena'} · Current ${game.formation} · Next wave ${next}: ${enemyNames}${boss}`;
    if(game.wave>1&&game.wave%6===0){const events=['mana','frenzy','bounty','fortify'],event=events[Math.floor(game.wave/6)%events.length];game.waveEvent=event;const labels={mana:'Mana Storm · regeneration +35%',frenzy:'Frenzy · enemies move faster',bounty:'Bounty Mark · wave reward +25%',fortify:'Fortified · more elites arrive'};A.say(labels[event],2.8);if(event==='mana'){game.eventRegenBoost=1.35;game.stats.manaRegen*=game.eventRegenBoost}}
    else game.waveEvent='';
    if(game.wave>1&&game.wave%10===0&&!game.milestones.has(game.wave)){game.milestones.add(game.wave);SS.addMagic(Math.round((100+game.wave*12)*(window.RealmSystem?.reward()||1)),`wave ${game.wave} milestone`);A.grantShield(Math.max(0,18-game.player.shield))}
  }
  const mutations=[['Surge','Regain 40 mana now; regeneration improves for this run.',game=>{game.player.mana=Math.min(game.stats.maxMana,game.player.mana+40);game.stats.manaRegen*=1.25}],['Bulwark','Gain up to 30 shield (60 max) and take 10% less damage for this run.',game=>{A.grantShield(30);game.stats.damageTaken*=.9}],['Overdrive','Gain 18% damage and 10% faster casting for this run.',game=>{game.stats.damage*=1.18;game.stats.cooldown*=.9}],['Reprieve','Recover 35 health and gain 10% movement speed.',game=>{if(game.mode!=='noheal')game.player.hp=Math.min(game.stats.maxHp,game.player.hp+35);game.stats.moveSpeed*=1.1}],['Harvest','Recover 8 mana on each kill for this run.',game=>{game.stats.killMana+=8}],['Deep Well','Gain 45 maximum mana and refill it.',game=>{game.stats.maxMana+=45;game.player.mana=game.stats.maxMana}],['Glass Sigil','Deal 42% more damage but take 18% more.',game=>{game.stats.damage*=1.42;game.stats.damageTaken*=1.18}],['Fleet Rune','Move 18% faster and dash 20% sooner.',game=>{game.stats.moveSpeed*=1.18;game.stats.dashCooldown*=.8}],['Effusion','Mana costs fall another 14% this run.',game=>{game.stats.cost*=.86}],['Longshot','Projectiles gain 35% speed and 12% damage.',game=>{game.stats.projectileSpeed*=1.35;game.stats.damage*=1.12}],['Mender','Heal 12 after every wave and gain 20 health now.',game=>{game.stats.waveHeal+=12;game.player.hp=Math.min(game.stats.maxHp,game.player.hp+20)}],['Execution','Critical chance rises by 14%.',game=>{game.stats.critChance+=.14}]];
  function bossDefeated(type,wave){const game=A.getGame();if(game.mode==='training')return;const unlocks={engine:'arc',mirror:'aim',voidboss:'gravity',frostboss:'crystal',splitboss:'fuse',tempestboss:'chain',broodboss:'shatter',sunboss:'ring',prismboss:'absorb'};if(!achievements[type]){achievements[type]=true;persistAchievements();SS.grantBlock(unlocks[type])}window.RealmSystem?.checkAchievements();if(game.bossDamage===0){SS.addMagic(Math.round((160+wave*12)*(window.RealmSystem?.reward()||1)),'flawless boss');achievements[type+'-flawless']=true;persistAchievements()}const pick=mutations.map((_,i)=>i).sort(()=>Math.random()-.5).slice(0,3);openPanel('Boss defeated · choose a free mutation',`<p>Wave ${wave} cleared. These effects last for this run. You can inspect your script before continuing.</p><div class="mutation-grid">${pick.map(i=>`<button data-mutation="${i}"><strong>${mutations[i][0]}</strong><small>${mutations[i][1]}</small></button>`).join('')}</div><button id="rewardLab">Open Spell Lab</button>`,'reward');$('closeFeature').style.display='none';$('featureContent').querySelectorAll('[data-mutation]').forEach(button=>button.onclick=()=>{const choice=mutations[Number(button.dataset.mutation)];choice[2](game);game.mutations.push(choice[0]);$('closeFeature').style.display='';closePanel(true);A.say(`${choice[0]} mutation active!`)});$('rewardLab').onclick=()=>{panel.classList.add('hidden');const original=SS.onEditorChange;SS.onEditorChange=open=>{original?.(open);if(!open){panel.classList.remove('hidden');SS.onEditorChange=original}};SS.openEditor?.('script')}}
  function phaseChanged(e,game){if(e.type==='frostboss'||e.type==='prismboss'){game.crystals.push({x:450,y:130,r:25,life:10},{x:520,y:470,r:25,life:10},{x:280,y:300,r:22,life:8})}else if(e.type==='tempestboss'){game.hazards.push({x:game.player.x,y:game.player.y,r:145,life:7,warn:1,tick:0,kind:'storm'})}else if(e.type==='broodboss'){game.hazards.push({x:e.x,y:e.y,r:175,life:9,warn:1.3,tick:0,kind:'poison'})}else if(e.type==='sunboss'){for(const [x,y] of [[240,160],[720,160],[240,440],[720,440]])game.hazards.push({x,y,r:72,life:7,warn:1,tick:0,kind:'flare'})}else game.hazards.push({x:e.x,y:e.y,r:120,life:5,warn:1.2,tick:0,kind:window.RealmSystem?.hazard()||'storm'})}
  function enemyDefeated(e,game){if(game.mode==='training')return;if(Math.random()<(e.trait?.3:.015)){const kind=['health','mana','shield'][Math.floor(Math.random()*3)];game.pickups.push({x:e.x,y:e.y,kind,life:9})}}
  function update(dt,game){const p=game.player;if(game.mobileSelected!==SS.selected){game.mobileSelected=SS.selected;spellButtons.forEach((button,i)=>button.classList.toggle('active',i===SS.selected))}if(game.mode==='training'){game.trainingTime+=dt;if(!game.enemies.length){const target=targetSelect.value||'dummy',enemy=A.makeEnemy(target,670,300);if(target!=='dummy'){enemy.speed=0;enemy.attack=999}game.enemies=[enemy]}if(game.enemies[0]?.type==='dummy')game.enemies[0].hp=game.enemies[0].max;game.trainingUiClock=(game.trainingUiClock||0)-dt;if(game.trainingUiClock<=0){game.trainingUiClock=.12;const seconds=Math.max(1,game.trainingTime),cost=game.trainingMana/Math.max(1,game.trainingCasts),regen=24*game.stats.manaRegen,rate=cost>0?Math.min(1/Math.max(.1,game.lastCastCooldown||.45),regen/cost):0;$('trainingReadout').textContent=`${Math.round(game.trainingDamage/seconds)} DPS · ${Math.round(game.trainingDamage/Math.max(1,game.trainingCasts))} damage/cast · ${Math.round(cost)} mana/cast · ${rate.toFixed(2)} sustainable casts/s`}return}
    if(game.bossInitializing)return;
    if(typeof navigator!=='undefined'&&navigator.getGamepads){const pad=navigator.getGamepads()[0];if(pad){for(const [key,axis,sign] of [['a',0,-1],['d',0,1],['w',1,-1],['s',1,1]])A.setKey(key,(pad.axes[axis]||0)*sign>.3);if(Math.hypot(pad.axes[2]||0,pad.axes[3]||0)>.2)A.setAim(p.x+(pad.axes[2]||0)*250,p.y+(pad.axes[3]||0)*250);A.setCasting(!!pad.buttons[7]?.pressed);if(pad.buttons[0]?.pressed&&!game.gamepadDash){A.dash();game.gamepadDash=true}if(!pad.buttons[0]?.pressed)game.gamepadDash=false}}
    for(const item of game.pickups){item.life-=dt;if(Math.hypot(item.x-p.x,item.y-p.y)<p.r+15){if(item.kind==='health'&&game.mode!=='noheal')p.hp=Math.min(game.stats.maxHp,p.hp+25);if(item.kind==='mana')p.mana=Math.min(game.stats.maxMana,p.mana+35);if(item.kind==='shield')A.grantShield(18);const hue=({health:'#8ce5a6',mana:'#f5c682',shield:'#88cfff'})[item.kind];A.particles?.(item.x,item.y,hue,18,item.kind==='shield'?'ring':'spark',.8);window.SpellAudio?.play(`pickup:${item.kind}`);item.life=0}}game.pickups=game.pickups.filter(v=>v.life>0);
    if(game.wave>=(window.RealmSystem?.intro?.()?12:8)&&game.wave%4===0&&game.hazardWave!==game.wave){game.hazardWave=game.wave;game.hazards.push({x:420+(game.wave%3)*70,y:220+(game.wave%2)*100,r:90,life:5,warn:1.4,tick:0,kind:window.RealmSystem?.hazard()||['lava','storm','collapse'][Math.floor(game.wave/4)%3]});window.SpellAudio?.play('hazard')}
    for(const h of game.hazards){
      h.life-=dt;h.warn=Math.max(0,h.warn-dt);h.tick-=dt;const inside=Math.hypot(p.x-h.x,p.y-h.y)<h.r;
      h.fx=(h.fx||0)-dt;if(h.fx<=0){const a=Math.random()*Math.PI*2,edge=.35+Math.random()*.6,styles={ice:['#91edff','shard'],lightning:['#e6f6ff','spark'],inferno:['#ff743b','ember'],spore:['#8fe078','spore'],void:['#ad6cff','mote'],prism:['#63eadb','shard'],crucible:[h.variant==='frost'?'#85def0':'#ff784c',h.variant==='frost'?'shard':'ember'],flare:['#ffe17e','spark']},fx=styles[h.kind]||['#ffffff88','mote'];A.particles?.(h.x+Math.cos(a)*h.r*edge,h.y+Math.sin(a)*h.r*edge,fx[0],1,fx[1],.28);h.fx=window.SpellFeatures?.settings?.lowEffects ? .22 : .07/Math.max(.5,game.fxQuality||1)}
      if(h.kind==='lightning'&&h.warn<=0&&!h.triggered){h.triggered=true;A.particles?.(h.x,h.y,'#e6f6ff',28,'spark',1.2);A.particles?.(h.x,h.y,'#a58cff',4,'ring',1);if(inside){A.hurt(18,false,'Tempest lightning');p.mana=Math.max(0,p.mana-20)}h.life=Math.min(h.life,.28);window.SpellAudio?.play('blast')}
      else if(h.kind==='ice'&&h.warn<=0&&inside){p.slippery=Math.max(p.slippery,.45);p.slow=Math.max(p.slow,.12)}
      else if(h.warn<=0&&h.tick<=0&&inside){
        if(h.kind==='storm')p.mana=Math.max(0,p.mana-15);
        else if(h.kind==='inferno'){A.hurt(7,false,'Furnace vent');p.burn=Math.max(p.burn,3)}
        else if(h.kind==='spore'){A.hurt(6,false,'Brood spores');p.poison=Math.max(p.poison,3.5)}
        else if(h.kind==='crucible'){A.hurt(8,false,'Twin Crucible floor');if(h.variant==='frost')p.slippery=Math.max(p.slippery,1.2);else p.burn=Math.max(p.burn,2.5)}
        else if(h.kind==='void'){A.hurt(10,false,'Void rift');p.slow=Math.max(p.slow,1)}
        else if(h.kind==='prism')A.hurt(10,false,'Prism cage');
        else A.hurt(h.kind==='lava'?7:11,false,`Arena ${h.kind}`);
        h.tick=.8
      }
      if(h.life<=0&&['collapse','frost','prism'].includes(h.kind)){if(h.kind==='prism'){for(let i=0;i<4;i++)game.crystals.push({x:h.x+Math.cos(i*Math.PI/2)*h.r*.72,y:h.y+Math.sin(i*Math.PI/2)*h.r*.72,r:20,life:5})}else game.crystals.push({x:h.x,y:h.y,r:28,life:5})}
    }game.hazards=game.hazards.filter(h=>h.life>0);
    game.replayClock=(game.replayClock||0)-dt;if(game.replayClock<=0){game.replayClock=.1;game.replay.push({x:p.x,y:p.y,wave:game.wave,enemies:game.enemies.slice(0,30).map(e=>({x:e.x,y:e.y,r:e.r,type:e.type}))});if(game.replay.length>150)game.replay.splice(0,game.replay.length-150)}
  }
  function draw(g,game){for(const h of game.hazards||[]){const hue=({lava:'#ff9c5f',frost:'#85def0',ice:'#91edff',storm:'#a58cff',lightning:'#e6f6ff',water:'#65d9ff',poison:'#79db72',spore:'#8fe078',inferno:'#ff6b3b',crucible:h.variant==='frost'?'#85def0':'#ff784c',flare:'#ffe17e',void:'#ad6cff',prism:'#63eadb',collapse:'#5de1d1',gravity:'#8f83ff'})[h.kind]||'#ff9c5f';g.save();g.fillStyle=h.warn>0?hue+'24':hue+'48';g.strokeStyle=hue;g.lineWidth=h.kind==='lightning'?4:3;g.beginPath();g.arc(h.x,h.y,h.r,0,Math.PI*2);g.fill();g.stroke();if(h.kind==='ice'){g.globalAlpha=.5;for(let i=-2;i<=2;i++){g.beginPath();g.moveTo(h.x-h.r,h.y+i*28);g.lineTo(h.x+h.r,h.y+i*28-35);g.stroke()}}else if(h.kind==='lightning'&&h.triggered){g.beginPath();g.moveTo(h.x-20,h.y-h.r-140);g.lineTo(h.x+12,h.y-h.r-75);g.lineTo(h.x-8,h.y-h.r-25);g.lineTo(h.x+5,h.y);g.stroke()}else if(h.kind==='prism'){g.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3,x=h.x+Math.cos(a)*h.r,y=h.y+Math.sin(a)*h.r;i?g.lineTo(x,y):g.moveTo(x,y)}g.closePath();g.stroke()}g.restore()}for(const item of game.pickups||[]){if(!A.drawSprite?.(`pickup_${item.kind}`,item.x,item.y,46)){g.fillStyle=({health:'#8ce5a6',mana:'#f5c682',shield:'#88cfff'})[item.kind];g.beginPath();g.arc(item.x,item.y,9,0,Math.PI*2);g.fill()}}for(const t of game.trails||[]){t.life-=.016;g.fillStyle=`rgba(137,240,207,${Math.max(0,t.life)})`;g.beginPath();g.arc(t.x,t.y,24*(1-t.life),0,7);g.fill()}game.trails=(game.trails||[]).filter(t=>t.life>0);if(game.player.shield>0){g.strokeStyle='#83d6ff';g.lineWidth=3;g.beginPath();g.arc(game.player.x,game.player.y,game.player.r+7,0,Math.PI*2);g.stroke()}}
  function screenshot(game){const source=$('arena'),canvas=document.createElement('canvas');canvas.width=960;canvas.height=710;const g=canvas.getContext('2d');g.fillStyle='#151d2b';g.fillRect(0,0,960,710);g.drawImage(source,0,0);g.fillStyle='#f3dfb7';g.font='bold 32px Georgia';g.fillText(`Spellforge · Wave ${game.wave}`,30,645);g.font='19px system-ui';g.fillText(`${game.kills} enemies · ${SS.current().map(x=>SS.block(x.id).name).join(' → ').slice(0,85)}`,30,681);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`spellforge-wave-${game.wave}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}
  function replay(game){if(!game.replay.length)return;openPanel('Last 15 seconds','<canvas id="replayCanvas" width="720" height="450"></canvas><p>Position replay of your last moments.</p>','replay');let i=0;const g=$('replayCanvas').getContext('2d');function tick(){if(panelKind!=='replay')return;const frame=game.replay[Math.min(i++,game.replay.length-1)];g.fillStyle='#141c2a';g.fillRect(0,0,720,450);g.fillStyle='#e8c280';g.font='18px system-ui';g.fillText(`Wave ${frame.wave}`,16,26);for(const e of frame.enemies){g.fillStyle=e.type==='voidboss'?'#aa80dc':'#e88a91';g.beginPath();g.arc(e.x*.75,e.y*.75,Math.max(4,e.r*.75),0,7);g.fill()}g.fillStyle='#85dec8';g.beginPath();g.arc(frame.x*.75,frame.y*.75,12,0,7);g.fill();if(i<game.replay.length)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
  function died(game){$('modal').querySelector('.death-actions')?.remove();const actions=document.createElement('div');actions.className='death-actions';actions.innerHTML='<button id="deathReplay">Replay last 15s</button><button id="deathCapture">Save build screenshot</button>';$('modal').append(actions);$('deathReplay').onclick=()=>replay(game);$('deathCapture').onclick=()=>screenshot(game)}
  window.SpellFeatures={settings,bindings,started,waveStarted,bossDefeated,phaseChanged,enemyDefeated,update,draw,died,settingsPanel,replay};
})();
