(() => {
  const entries=[
    ['chaser','Red Pursuer','#ed8682','A direct, aggressive pursuer.','Runs toward your position and closes gaps quickly.','Damages you by contact.','Keep moving across open lanes and fire while retreating.','The simplest foe becomes dangerous in a crowd.'],
    ['shooter','Violet Shooter','#d48ac7','A ranged enemy that guards its distance.','Approaches until it has a firing lane, then backs away if you get close.','Fires a single aimed bullet.','Use cover to close the gap, then keep pressure on it.','Its preferred distance makes it a nuisance behind tanks.'],
    ['charger','Amber Charger','#f2ac6c','A fast attacker with a visible windup.','Moves into range, pauses to aim, then rushes forward.','Deals heavy contact damage during a charge.','Move sideways when its aiming line appears.','A missed charge gives you a short opening.'],
    ['splitter','Green Splitter','#90c879','One enemy that becomes two.','Chases at a steady pace.','Releases two small swarms when defeated.','Leave space for the swarms before landing the finishing hit.','Area spells handle its second life well.'],
    ['swarm','Green Swarm','#b0e783','A small fragment of a defeated Splitter.','Sprints directly toward you.','Deals light but frequent contact damage.','Wide Forms and burst effects clear them quickly.','Small enemies still count toward your Magic.'],
    ['tank','Stone Tank','#9b91c4','A slow, heavily armored pursuer.','Advances slowly and keeps following.','Hits hard on contact.','Pierce, poison, and sustained damage work well.','Its bulk can shield ranged enemies behind it.'],
    ['wisp','Azure Wisp','#80d8e4','An evasive ranged enemy.','Weaves sideways while keeping its distance.','Fires two angled bullets at once.','Lead your shots or use Seek to catch it.','Its paired shots punish running straight toward it.'],
    ['golden','Golden Wanderer','#f1ca78','The familiar round yellow enemy.','Moves into medium range.','Fires an eight-way radial burst.','Watch the gaps between bullets and keep circling.','It remains a regular enemy, separate from the Engine.'],
    ['sentinel','Yellow Sentinel','#e4b85c','A slow, sturdy four-sided minion.','Creeps forward while holding its firing position.','Fires bullets from all four sides.','Approach between its firing directions.','The Twelvefold Engine can release one during a fight.'],
    ['crimson','Crimson Castle','#872b42','A slow turret with a single forward barrel.','Turns to face you and inches closer.','Launches a homing missile every six seconds.','Use rocks or a sharp dash to break the missile path.','Its missile stops steering after 2.5 seconds.'],
    ['engine','Twelvefold Engine','#ffe083','A twelve-armed yellow boss.','Moves around the arena and keeps a useful firing distance.','Launches homing missiles, releases Yellow Sentinels, then vents fireballs and molten floor zones.','Dash across the missiles and leave a furnace marker before it opens.','Its health, missile count, and attack rate grow in later encounters.'],
    ['mirror','Counterforge','#a9ebeb','A boss shaped by your own active spell.','Presses toward casting range, strafes, and dodges incoming shots.','Uses your current spell script with reduced damage, then projects three firing afterimages at the arena corners.','Switch loadouts to alter its copy and move when the corner images appear.','Later Counterforge encounters cast and dodge more quickly.'],
    ['voidboss','Void Sovereign','#8c5cc0','A dangerous boss that feeds on successful attacks.','Circles at range while purple fireballs orbit its body.','Casts its frozen swirl, throws orbiting fireballs, and opens slowing void rifts beneath you.','Move when the swirl freezes, then leave the marked rift before attacking.','Its explosion happens even if you evade it; hitting you restores its health.'],
    ['voidmage','Void Mage','#a276cf','A distant caster found after the Void Sovereign.','Keeps its distance but needs no line of sight to cast.','Its swirl freezes for 1.2 seconds before exploding for 40 damage, with no range limit.','Watch for the fixed purple ring and leave it before detonation.','Distance alone cannot stop this spell.'],
    ['healer','Verdant Healer','#83d7ae','A support enemy that restores nearby allies.','Keeps away from the player and near its companions.','Heals nearby enemies in pulses.','Pick it off before focusing a tank.','Its healing pulse is visible as a green link.'],
    ['sniper','Rose Sniper','#d9749d','A patient long-range shooter.','Retreats when approached.','Locks a red line for 0.9 seconds, then fires a fast bullet.','Cross the aim line before the shot.','It cannot retarget once the line locks.'],
    ['burrower','Burrower','#9675a9','A tunneling ambusher.','Vanishes briefly and resurfaces near you.','Deals contact damage after emerging.','Keep moving while the ground ring is visible.','It cannot be hit while underground.'],
    ['shieldbearer','Shield Bearer','#bdac74','A tough enemy with a directional guard.','Walks steadily toward you.','Its front shield reduces incoming damage.','Circle behind it or use a wide Ring spell.','A heavily used Ember build can draw heat-resistant guards.'],
    ['mimic','Spell Mimic','#90cbd3','A lesser reflection of your magic.','Keeps medium range while strafing.','Copies one Form from your active spell at reduced strength.','Watch your own Form and switch to a more manageable slot.','Counterforge is not the only enemy that studies your spells.'],
    ['frostboss','Glacial Architect','#96e4ee','A boss that shapes the arena into a trap.','Keeps a cautious range while placing temporary crystal walls.','Fires paired ice bolts, builds walls, and temporarily freezes a huge section of floor.','Use short taps on ice; momentum continues after you release a movement key.','At half health its ice field grows and lasts longer.'],
    ['splitboss','Twin Crucible','#f0a3ad','A boss that refuses to end as one.','Strafes while firing a broad fan.','Marks paired Ember and Frost zones before splitting into rushing and ranged halves.','Thread between the paired zones and save a wide attack for the two halves.','Its halves share a beginning, but fight differently.'],
    ['splitA','Crucible Ember','#ffb077','The rushing half of Twin Crucible.','Charges straight toward the player.','Deals close-range contact damage.','Back away while attacking the ranged half.','One half of a broken forge.'],
    ['splitB','Crucible Ash','#e2a2e9','The ranged half of Twin Crucible.','Keeps its distance.','Fires pairs of aimed bullets.','Close the gap after the rushing half falls.','The other half of a broken forge.'],
    ['cinderhound','Cinder Hound','#ff744d','An Ember Foundry hunting construct.','Rushes directly at you and bursts forward after venting heat.','Its bite ignites you for several seconds.','Turn across its charge instead of retreating in a straight line.','Cinder Hounds only form where a forge has burned long enough.'],
    ['rimeweaver','Rime Weaver','#70dff3','A Frost Bastion artillery insect.','Maintains long range behind crystal cover.','Fires three slowing ice needles.','Destroy its firing lane or dash across all three needles at once.','Its six legs anchor it against its own recoil.'],
    ['thunderhead','Thunderhead','#c68aff','A Storm Crucible discharge drone.','Orbits you rapidly instead of holding one firing line.','Releases six-way bursts that drain mana.','Move through the rotating gap before the next discharge.','Its vanes store the charge stolen from failed spells.'],
    ['vectorscribe','Vector Scribe','#8d63dc','A Storm Crucible path-calculation construct.','Keeps its distance while drawing a route through the arena.','Shows a curved warning line, locks it, then sends four linked spikes along the frozen path.','Move only after the curve stops changing; the spike chain cannot retarget.','Its route bends around cover because collision is merely another variable.'],
    ['sporebrute','Spore Brute','#79db72','A heavy creature exclusive to the Venom Wilds.','Walks straight into close range and roots briefly.','Poisons on contact and leaves toxic ground behind.','Pull it away from healers before committing to damage.','Its armor is cultivated rather than forged.'],
    ['sunlancer','Sun Lancer','#ffe17e','A Radiant Court execution construct.','Retreats to maintain a long, clear lane.','Locks its aim, then fires a high-damage ray.','Cross the aim line during its short charge.','Every lance is aligned to the Court’s artificial sun.'],
    ['riftstalker','Rift Stalker','#ad6cff','A Void Expanse ambusher.','Approaches, vanishes, and reappears near your path.','Strikes immediately after a short teleport tell.','Keep moving perpendicular to its last approach.','The hollow core marks the space it removed from itself.'],
    ['shardsmith','Shard Smith','#5de1d1','A Crystal Labyrinth builder.','Advances carefully while constructing cover.','Raises crystal stakes and fires through the new lane.','Force it to build away from the center of the arena.','Every wall is another tool for the Prism Warden.'],
    ['graviton','Graviton','#8f83ff','A dense Gravity Well control engine.','Holds medium range and pulls you off your route.','Fires slowing gravity packets in a spread.','Dash after the pull begins to preserve your intended direction.','Its orbit plates never agree on which way is down.'],
    ['tempestboss','Tempest Crown','#c68aff','The sovereign turbine of the Storm Crucible.','Circles while its six vanes gather charge.','Alternates rotating storms, marked lightning strikes, and water volleys that make movement slippery.','Leave lightning circles early; steer gently after a water orb hits.','Every Thunderhead is a fragment of its crown.'],
    ['broodboss','Brood Cathedral','#79db72','A walking fungal fortress rooted in the Venom Wilds.','Advances slowly while seeding the arena.','Fires poison fans, grows Spore Brutes, and blooms rings of toxic spore pods.','Move through the unfinished gap before the pod ring activates.','The cathedral is an ecosystem that learned to hunt.'],
    ['sunboss','Solar Regent','#ffe17e','The central weapon of the Radiant Court.','Maintains range while turning its aperture toward you.','Combines radial rays and a heavy lance with burning solar fireball fans and flare zones.','Use cover for the lance, then cross the fireball fan before the flare closes.','The Court mistakes perfect geometry for mercy.'],
    ['prismboss','Prism Warden','#5de1d1','The architect at the heart of the Crystal Labyrinth.','Moves methodically as the available floor disappears.','Creates walls, fires shard fans, and closes a hexagonal prism cage that crystallizes at its edges.','Exit the hexagon before it solidifies or reserve a route between the new crystals.','The labyrinth is the shape of its unfinished thought.'],
    ['furnacehound','Furnace Hound','#ff7045','An oversized forge predator that guards dangerous routes.','Charges in a wedge and scorches the ground behind it.','Spits three fireballs and vents an inferno around its body.','Cut sideways through the fireball fan, then punish the cooling vent.','Its hollow furnace was made to consume failed constructs.'],
    ['avalancheknight','Avalanche Knight','#8de8f3','A walking ice bulwark from the deepest Bastion halls.','Advances behind a heavy shield and denies wide lanes.','Raises an ice field and fires a five needle frost fan.','Use cover until the fan passes; do not make long turns on its ice.','A whole collapsed glacier is sealed inside its armor.'],
    ['stormchoir','Storm Choir','#c68aff','Three synchronized storm cores housed in one conductor.','Floats around the edge of its preferred firing range.','Marks a triangle of lightning strikes around your position.','Leave the entire triangle before looking for a firing lane.','Each voice predicts where the other two expect you to dodge.'],
    ['sporemonarch','Spore Monarch','#83dc70','A royal fungal mass that turns attrition into armor.','Drifts slowly toward established spore ground.','Blooms a large poison field and restores part of its health.','Burst it between blooms and never fight inside the spores.','The crown is a colony voting on where to grow next.'],
    ['gravityjailer','Gravity Jailer','#9187ff','A dense prison engine that carries its own orbit.','Holds medium range while bending escape routes inward.','Creates a gravity field and fires five radial gravity packets.','Dash after the pull begins and pass between two packets.','Its prisoners are the fragments permanently orbiting its core.'],
  ].map(([id,name,color,summary,movement,attacks,tip,lore])=>({id,name,color,summary,movement,attacks,tip,lore,boss:['engine','mirror','voidboss','frostboss','splitboss','tempestboss','broodboss','sunboss','prismboss'].includes(id)}));
  const byId=Object.fromEntries(entries.map(e=>[e.id,e])),key='spellforge-enemy-journal-v1';
  let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{}
  const records=Object.fromEntries(entries.map(e=>{const row=saved[e.id]||{};return[e.id,{seen:Number.isFinite(row.seen)?Math.max(0,Math.floor(row.seen)):0,kills:Number.isFinite(row.kills)?Math.max(0,Math.floor(row.kills)):0}]}));
  let selected=entries[0].id,filter='all',openState=false;
  const card=document.createElement('section');card.className='card panel journal-card';card.innerHTML='<h2>Enemy Journal</h2><p class="muted">Discover enemies and uncover their tactics as you fight.</p><button class="journal-open" id="openJournal">Open Enemy Journal</button><small id="journalProgress"></small>';
  document.querySelector('.side').append(card);
  const modal=document.createElement('div');modal.id='enemyJournal';modal.className='journal-overlay hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','Enemy Journal');
  modal.innerHTML='<div class="journal-window"><div class="journal-header"><div><small>THE BESTIARY</small><h2>Enemy Journal</h2><p>Every encounter adds to your field notes.</p></div><button id="closeJournal" class="journal-close">Done</button></div><div class="journal-filters" id="journalFilters"></div><div class="journal-body"><div class="journal-list" id="journalList"></div><div class="journal-detail" id="journalDetail"></div></div></div>';
  document.body.append(modal);
  const $=id=>document.getElementById(id);
  function stage(entry){const r=records[entry.id];if(!r.seen)return 0;if(entry.boss)return r.kills>=3?5:r.kills>=2?4:r.kills>=1?3:r.seen>=2?2:1;return r.seen>=20&&r.kills>=10?5:r.kills>=5?4:r.seen>=8?3:r.seen>=3?2:1}
  function nextNote(entry,level){const r=records[entry.id];if(level>=5)return'Field notes complete.';if(entry.boss)return level===1?'Encounter it once more to reveal movement.':level===2?'Defeat it to reveal its attacks.':level===3?'Defeat it again for a survival tip.':'Defeat it a third time for the final note.';return level===1?`Encounter ${Math.max(0,3-r.seen)} more to reveal movement.`:level===2?`Encounter ${Math.max(0,8-r.seen)} more to reveal attacks.`:level===3?`Defeat ${Math.max(0,5-r.kills)} more for a survival tip.`:'Reach 20 encounters and 10 defeats for the final note.'}
  function portrait(entry,level){
    const c=level?entry.color:'#465066',base=`<circle cx="60" cy="61" r="24" fill="${c}" stroke="#2a2637" stroke-width="5"/>`;
    if(!level)return'<svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="61" r="26" fill="#40495c"/><text x="60" y="72" text-anchor="middle" fill="#9ca8bc" font-size="29">?</text></svg>';
    return`<img class="journal-sprite" src="assets/images/current/${entry.id}.png" alt="${entry.name}">`;
    /* Procedural portraits remain below as an offline reference and fallback design source.
    let extras='';
    if(entry.id==='engine')extras=Array.from({length:12},(_,i)=>`<rect x="78" y="55" width="27" height="10" rx="2" fill="#d7a852" transform="rotate(${i*30} 60 60)"/>`).join('')+base;
    else if(entry.id==='voidboss')extras=`<circle cx="60" cy="61" r="34" fill="none" stroke="#c98af1" stroke-width="4"/>${base}${level>=3?Array.from({length:6},(_,i)=>{const a=i*Math.PI/3;return`<circle cx="${60+Math.cos(a)*43}" cy="${61+Math.sin(a)*43}" r="6" fill="#d7a4ff"/>`}).join(''):''}`;
    else if(entry.id==='crimson')extras=`<rect x="34" y="39" width="52" height="45" fill="#682139"/><rect x="40" y="31" width="10" height="15" fill="#a94b59"/><rect x="69" y="31" width="10" height="15" fill="#a94b59"/>${level>=3?'<rect x="83" y="56" width="27" height="10" fill="#b44e5a"/>':''}`;
    else if(entry.id==='voidmage')extras=`<path d="M60 22 L87 88 L33 88 Z" fill="#39205e" stroke="#a276cf" stroke-width="4"/><circle cx="60" cy="63" r="15" fill="${c}"/>`;
    else if(entry.id==='sentinel')extras=`<rect x="41" y="41" width="38" height="38" fill="${c}"/>${level>=3?'<path d="M55 23h10v18h-10zM55 79h10v18H55zM23 55h18v10H23zM79 55h18v10H79z" fill="#8a6a35"/>':''}`;
    else if(entry.id==='frostboss')extras=`<path d="M60 23 L87 60 L60 99 L33 60 Z" fill="${c}" stroke="#e2ffff" stroke-width="4"/>${level>=3?'<path d="M60 19V5M30 60H13M90 60h17M60 102v12" stroke="#a9f6ff" stroke-width="5"/>':''}`;
    else if(entry.id==='splitboss')extras=`<path d="M60 35 A27 27 0 1 0 60 88 Z" fill="#ffb077"/><path d="M60 35 A27 27 0 1 1 60 88 Z" fill="#e2a2e9"/>${level>=3?'<path d="M60 20v83" stroke="#392637" stroke-width="5"/>':''}`;
    else if(entry.id==='shieldbearer')extras=`${base}<path d="M82 33 Q111 60 82 88 L72 78 V43 Z" fill="#eadba8" stroke="#765d42" stroke-width="3"/>`;
    else if(entry.id==='healer')extras=`${base}<path d="M55 42h10v14h14v10H65v14H55V66H41V56h14z" fill="#d9ffe9"/>`;
    else if(entry.id==='sniper')extras=`${base}<rect x="78" y="56" width="31" height="8" rx="2" fill="#ffd2df"/>`;
    else extras=base+(level>=3&&['shooter','wisp','mirror','golden'].includes(entry.id)?'<rect x="78" y="56" width="23" height="10" rx="3" fill="#e6d3ff"/>':'');
    const study=level>=2?`<path d="M20 82 Q12 60 23 38" fill="none" stroke="${c}" stroke-width="3" opacity=".7"/>`:'';
    const attack=level>=3?`<circle cx="98" cy="29" r="5" fill="${c}"/>`:'';
    const mastery=level>=4?`<circle cx="60" cy="60" r="48" fill="none" stroke="${c}" stroke-width="3" stroke-dasharray="7 5"/>`:'';
    const complete=level>=5?'<path d="M60 3l4 9 10 1-7 7 2 10-9-5-9 5 2-10-7-7 10-1z" fill="#f6d184"/>':'';
    return`<svg viewBox="0 0 120 120" aria-hidden="true">${extras}${study}${attack}${mastery}${complete}</svg>`*/
  }
  function note(label,value,visible){return`<div class="journal-note"><b>${label}</b><p>${visible?value:'Unknown · keep studying this enemy'}</p></div>`}
  function progress(){const found=entries.filter(e=>records[e.id].seen).length;$('journalProgress').textContent=`${found} / ${entries.length} discovered`}
  function render(){
    progress();if(!openState)return;
    const filters=$('journalFilters');filters.innerHTML='';for(const [id,label] of [['all','All'],['regular','Regular'],['boss','Bosses']]){const b=document.createElement('button');b.className=filter===id?'active':'';b.textContent=label;b.onclick=()=>{filter=id;render()};filters.append(b)}
    const visible=entries.filter(e=>filter==='all'||(filter==='boss')===e.boss);if(!visible.some(e=>e.id===selected))selected=visible[0].id;
    const list=$('journalList');list.innerHTML='';for(const e of visible){const level=stage(e),r=records[e.id],b=document.createElement('button');b.className='journal-entry'+(e.id===selected?' active':'')+(level?'':' unknown');b.innerHTML=`<span class="journal-entry-icon">${portrait(e,level)}</span><span><strong>${level?e.name:'Unknown entity'}</strong><small>${level?`${r.seen} seen · ${r.kills} defeated`:'Not encountered'}</small></span>`;b.onclick=()=>{selected=e.id;render()};list.append(b)}
    const e=byId[selected],level=stage(e),r=records[e.id],detail=$('journalDetail');
    const affinity=window.RealmSystem?.affinity(e.id)||'Unbound';detail.innerHTML=`<div class="journal-hero"><div class="journal-portrait">${portrait(e,level)}</div><div><small>${e.boss?'BOSS':'ENEMY'} · ${affinity.toUpperCase()} AFFINITY · RESEARCH ${level}/5</small><h3>${level?e.name:'Unknown entity'}</h3><p>${level?e.summary:'Encounter this enemy to begin its entry.'}</p></div></div><div class="journal-research">${level?`${r.seen} encounters · ${r.kills} defeats · ${nextNote(e,level)}`:'No field notes yet.'}</div>${level?note('Movement',e.movement,level>=2)+note('Attacks',e.attacks,level>=3)+note('Survival tip',e.tip,level>=4)+note('Final observation',e.lore,level>=5):''}`;
  }
  function save(){try{localStorage.setItem(key,JSON.stringify(records))}catch{}}
  function seen(id){if(!records[id])return;records[id].seen++;save();render()}
  function defeated(id){if(!records[id])return;if(!records[id].seen)records[id].seen=1;records[id].kills++;save();render()}
  function open(){if(openState)return;openState=true;modal.classList.remove('hidden');api.onToggle?.(true);render();$('closeJournal').focus()}
  function close(){if(!openState)return;openState=false;modal.classList.add('hidden');api.onToggle?.(false)}
  const api={entries,records,stage:id=>byId[id]?stage(byId[id]):0,seen,defeated,open,close,onToggle:null};
  $('openJournal').onclick=open;$('closeJournal').onclick=close;modal.addEventListener('pointerdown',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&openState){e.preventDefault();close()}});
  window.EnemyJournal=api;progress()
})();
