(() => {
  const groups = {
    element: [
      ['ember','Ember','Burns over time',0],['frost','Frost','Slows targets',300],['storm','Storm','Jumps lightning',460],['void','Void','Steals health',650],
      ['venom','Venom','Stacks poison',820],['radiant','Radiant','Finishes weakened foes',980],['siphon','Siphon','Restores mana on hit',1200],['rupture','Rupture','Weakens enemy armor',1500],
      ['gravity','Gravity','Pulls nearby enemies together',1850],['crystal','Crystal','Leaves temporary crystal cover',1950],
    ],
    shape: [
      ['bolt','Bolt','One accurate shot',0],['fan','Fan','Three spreading shots',300],['lance','Lance','Heavy piercing shot',460],['nova','Nova','Eight directions',650],
      ['scatter','Scatter','Five close-range shots',820],['orb','Orb','Slow heavy projectile',980],['spiral','Spiral','Rotating four-shot pattern',1200],['barrage','Barrage','Rapid narrow volley',1500],['beam','Focused Beam','Three fast parallel shots in a tight line',1050],
      ['arc','Arc','Instant short lightning strike',1900],['ring','Ring','Expanding wave around the caster',2050],['mine','Mine','Waits for an enemy to approach',2200],
    ],
    elasticity: [
      ['straight','Straight','Clears motion rules',0],['bounce','Bounce','Reflects from stone',300],['seek','Seek','Adds steering velocity toward enemies',460],['orbit','Orbit','Circles the caster',650],
      ['accelerate','Accelerate','Gains speed and power',820],['boomerang','Boomerang','Returns to caster',980],['wave','Wave','Weaves side to side',1200],['linger','Linger','Moves slowly, lasts longer',1500],
      ['tether','Tether','Damages along a line back to you',1900],['return','Return','Refunds mana when caught',2050],
    ],
    behavior: [
      ['impact','Impact','Clears event rules',0],['split','Split','Forks into two shots',300],['echo','Echo','Repeats after a delay',460],['detonate','Detonate','Area damage on hit',650],
      ['pierce','Pierce','Passes through enemies',820],['chain','Chain','Jumps to another target',980],['shatter','Shatter','Fragments on walls',1200],['knockback','Knockback','Pushes targets away',1500],
      ['mark','Mark','Marks targets for bonus damage and seeking',1800],['absorb','Absorb','Consumes enemy bullets to grow',1950],['fuse','Fuse','Merges nearby friendly shots',2100],
    ],
    control: [
      ['repeat','Repeat Next Form','Fires the next form several times',700],['wait','Wait','Delays the next form',500],
      ['ifNear','If Enemy Near','Only fires the next form near enemies',900],['ifWounded','If Wounded','Only fires the next form at low health',1100],
      ['onHit','On Hit','Attach forms until End Event',1200],['onKill','On Kill','Attach forms until End Event',1350],['onBounce','On Bounce','Attach forms until End Event',1450],['onExpire','On Expire','Attach forms until End Event',1550],['endEvent','End Event','Return to the main spell',0],
      ['ifStatus','If Target Status','Run a branch when a target has an effect',1300],['ifMana','If Mana Below','Run a branch at low mana',1400],['ifSurrounded','If Surrounded','Run a branch near a crowd',1450],['else','Else','Run when the previous condition is false',0],['endIf','End If','Finish a conditional branch',0],
      ['repeatGroup','Repeat Group','Repeat connected forms up to three times',1650],['endRepeat','End Repeat','Finish a repeated group',0],['aim','Aim','Choose how later forms acquire targets',1500],
    ],
  };
  const kinds=Object.keys(groups),defaults={element:'ember',shape:'bolt',elasticity:'straight',behavior:'impact'};
  const definitions=Object.fromEntries(kinds.map(kind=>[kind,groups[kind].map(([id,name,detail,price])=>({id,name,detail,price,kind}))]));
  const parameters={bounce:{label:'bounces',min:1,max:4,step:1,default:2},fan:{label:'spread',min:.1,max:.5,step:.05,default:.25},echo:{label:'delay',min:.15,max:.7,step:.05,default:.3},nova:{label:'rays',min:6,max:12,step:1,default:8},split:{label:'angle',min:.3,max:1,step:.05,default:.65},repeat:{label:'times',min:2,max:4,step:1,default:2},wait:{label:'seconds',min:.1,max:.8,step:.1,default:.3},ifNear:{label:'range',min:100,max:400,step:25,default:220},ifWounded:{label:'HP ≤ %',min:20,max:80,step:10,default:50},ifStatus:{label:'1 Frost · 2 Burn · 3 Poison',min:1,max:3,step:1,default:1},ifMana:{label:'mana below %',min:10,max:90,step:10,default:40},ifSurrounded:{label:'enemies',min:2,max:8,step:1,default:3},repeatGroup:{label:'times',min:2,max:3,step:1,default:2},aim:{label:'1 Mouse · 2 Near · 3 Weak · 4 Random',min:1,max:4,step:1,default:1}};
  const byId=new Map(Object.values(definitions).flat().map(b=>[b.id,b]));
  const talents=[
    ['vitality','Vitality','+40 health at rank 1, then +12 per rank (max 5)',450],['constitution','Constitution','+10 maximum health per rank (max 3)',1400],['reservoir','Reservoir','+30 maximum mana per rank (max 8)',450],['flow','Mana Flow','+30% mana regeneration per rank (max 8)',620],
    ['stride','Swift Step','+25% movement speed for dodging',620],['focus','Arcane Focus','+16% spell damage per rank (max 10)',800],['velocity','Velocity','+35% projectile speed',800],
    ['dash','Quick Dash','Dash recharges 35% faster',950],['renewal','Renewal','+20 wave healing at rank 1, then +5 per rank (max 4)',950],['ward','Warding','Take 20% less damage',1150],
    ['fortune','Fortune','+25% Magic from kills and waves per rank (max 8)',900],['precision','Precision','18% chance for a double-damage hit',1300],['harvest','Harvest','Restore 12 mana on a kill',1450],
    ['secondWind','Second Wind','Survive one fatal hit each run with 45 HP',1650],['quickcast','Quickcast','22% shorter cast cooldown',1650],['efficiency','Efficiency','20% lower mana cost',1650],
    ['moreInk','Longer Script','Five more script blocks',1800],['grimoire','Grand Grimoire','Another five script blocks',2300],
    ['phaseDash','Phase Dash','Dash destroys nearby enemy bullets',1900],['killSurge','Kill Surge','Kills briefly double mana regeneration',1850],['aegis','Aegis','A clean dash through a bullet grants a small shield',2100],
    ['boltMaster','Bolt Mastery','Bolt, Beam, and Arc deal 20% more damage',2200],['burstMaster','Burst Mastery','Fan, Nova, Ring, and Scatter deal 20% more damage',2200],
    ['momentum','Momentum','Moving continuously builds up to 15% more spell damage',2400],['bastion','Bastion','Take 12% less damage while near cover',2300],
    ['prosperity','Prosperity','Bosses award 20% more Magic',2600],['overcharge','Overcharge','At full mana, your first cast deals 25% more damage',2450],
    ['specialist','Form Specialist','Your most-used Form gains 18% damage',2550],
  ].map(([id,name,detail,price])=>({id,name,detail,price,kind:'talent'}));
  const storeKey='spellforge-roguelite-v1';let saved={};try{saved=JSON.parse(localStorage.getItem(storeKey)||'{}')||{}}catch{}
  let magic=Number.isFinite(saved.magic)?Math.max(0,Math.floor(saved.magic)):0;
  const permanent=new Set(Array.isArray(saved.permanent)?saved.permanent:[]),upgrades=new Set(Array.isArray(saved.upgrades)?saved.upgrades:[]);
  const rankCaps={focus:10,reservoir:8,flow:8,fortune:8,vitality:5,renewal:4,constitution:3};
  const ranks=Object.fromEntries(Object.keys(rankCaps).map(id=>[id,Number.isInteger(saved.ranks?.[id])?Math.max(0,Math.min(rankCaps[id],saved.ranks[id])):id==='focus'&&Number.isInteger(saved.focusRank)?Math.max(0,Math.min(rankCaps[id],saved.focusRank)):(upgrades.has(id)?1:0)]));
  function talentRank(id){return id in rankCaps?ranks[id]:Number(upgrades.has(id))}
  function talentCap(id){return rankCaps[id]||1}
  function talentPrice(id){const t=talents.find(v=>v.id===id),growth={focus:1.18,vitality:1.31,renewal:1.26,constitution:1.3}[id]||1.16;return !t?0:id in rankCaps?Math.round(t.price*Math.pow(growth,ranks[id])/10)*10:t.price}
  let nextUid=1,selected=0,note='',blueprints=Array.isArray(saved.blueprints)?saved.blueprints.slice(0,40):[];
  function block(id){return byId.get(id)}
  function owned(id){const b=block(id);return !!b&&(b.price===0||permanent.has(id))}
  const fresh=()=>['ember','straight','impact','bolt'].map(id=>({uid:nextUid++,id}));
  function restoreScript(raw){if(!Array.isArray(raw))return fresh();const script=raw.filter(item=>owned(typeof item==='string'?item:item?.id)).slice(0,32).map(item=>{const id=typeof item==='string'?item:item.id,spec=parameters[id],value=spec?Math.max(spec.min,Math.min(spec.max,Number(item.value??spec.default))):undefined;return{uid:nextUid++,id,...(spec?{value}:{})}});return script.length?script:fresh()}
  const scripts=Array.from({length:3},(_,i)=>{
    if(saved.scripts?.[i])return restoreScript(saved.scripts[i]);
    const old=saved.loadouts?.[i];if(old){const ids=[old.element,old.elasticity,old.behavior,old.shape].filter(Boolean);return restoreScript(ids)}
    return fresh();
  });
  const $=id=>document.getElementById(id),panel=document.querySelector('.side .panel');
  panel.innerHTML='<h2>Spellforge</h2><p class="muted">Build connected scripts. Every block in the stack runs from top to bottom.</p><div class="magic-bank">✦ <strong id="magicAmount">0</strong> Magic <small>Saved between runs</small></div><div id="spellPanel"></div>';
  const style=document.createElement('style');style.textContent=`.magic-bank{background:#111827;border:1px solid #5b523e;border-radius:8px;padding:10px;margin:11px 0;color:#f2ca86;font-weight:800}.magic-bank small{display:block;color:#aeb9c7;font-size:11px;font-weight:400;margin-top:2px}.spell-slots{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.spell-slots button{background:#2b364b;border:1px solid #59677e;border-radius:7px;padding:8px 2px;color:#ece6d9;font-size:12px}.spell-slots button.active{background:#4e3d49;border-color:#e9c184}.summary{background:#111827;border-radius:8px;padding:12px;line-height:1.5;color:#e7e1d7;margin:10px 0;font-size:12px;max-height:100px;overflow:auto}.lab-launch{width:100%;background:#d7ad6b;color:#211e24;border:0;border-radius:9px;padding:12px;font-weight:900;margin-top:7px}.lab-launch.secondary{background:#34435e;color:#f5e9d8;border:1px solid #7989a2}.spell-note{font-size:11px;color:#e7c895;margin-top:9px;line-height:1.4}`;document.head.append(style);
  const plain=s=>s.map(x=>({id:x.id,...(x.value===undefined?{}:{value:x.value})}));
  function save(){try{localStorage.setItem(storeKey,JSON.stringify({magic,permanent:[...permanent],upgrades:[...upgrades],ranks,focusRank:ranks.focus,scripts:scripts.map(plain),blueprints}))}catch{}}
  let deferredSave=0;function scheduleSave(){if(deferredSave)return;const commit=()=>{deferredSave=0;save()};if(typeof requestIdleCallback==='function')deferredSave=requestIdleCallback(commit,{timeout:1600})||1;else deferredSave=setTimeout(commit,750)||1}
  function tell(message){note=message;api.onMessage?.(message);render()}
  function maxBlocks(){return 18+(upgrades.has('moreInk')?5:0)+(upgrades.has('grimoire')?5:0)}
  const histories=Array.from({length:3},()=>({past:[],future:[]}));
  function checkpoint(){const h=histories[selected];h.past.push(plain(scripts[selected]));if(h.past.length>50)h.past.shift();h.future=[]}
  function insertBlock(id,index){const b=block(id);if(!b)return false;if(!owned(id)){api.onUnlockRequest?.(id);tell(`${b.name} is locked. Buy it permanently for ${b.price} Magic.`);return false}const s=scripts[selected];if(s.length>=maxBlocks()){tell(`Script is full (${maxBlocks()} blocks). Buy Longer Script to add more.`);return false}checkpoint();const spec=parameters[id];s.splice(Math.max(0,Math.min(s.length,index)),0,{uid:nextUid++,id,...(spec?{value:spec.default}:{})});save();tell(`${b.name} connected to Spell ${selected+1}.`);return true}
  function setParam(uid,raw){const item=scripts[selected].find(v=>v.uid===uid);if(!item)return false;const spec=parameters[item.id],n=Number(raw);if(!spec||!Number.isFinite(n))return false;checkpoint();item.value=Math.max(spec.min,Math.min(spec.max,Math.round(n/spec.step)*spec.step));save();render();return true}
  function moveBlock(from,to){const s=scripts[selected];if(from<0||from>=s.length)return false;checkpoint();const [item]=s.splice(from,1);if(to>from)to--;s.splice(Math.max(0,Math.min(s.length,to)),0,item);save();render();return true}
  function removeBlock(index){const s=scripts[selected];if(index<0||index>=s.length)return false;checkpoint();const [item]=s.splice(index,1);save();tell(`${block(item.id).name} removed from the script.`);return true}
  function duplicateRange(from,to,index){const s=scripts[selected],part=s.slice(from,to).map(x=>({...x,uid:nextUid++}));if(!part.length||s.length+part.length>maxBlocks())return false;checkpoint();s.splice(index,0,...part);save();render();return true}
  function moveRange(from,to,index){const s=scripts[selected];if(from<0||to> s.length||from>=to)return false;checkpoint();const part=s.splice(from,to-from);if(index>from)index-=part.length;s.splice(Math.max(0,Math.min(s.length,index)),0,...part);save();render();return true}
  function removeRange(from,to){const s=scripts[selected];if(from<0||to>s.length||from>=to)return false;checkpoint();s.splice(from,to-from);save();render();return true}
  function undo(){const h=histories[selected];if(!h.past.length)return false;h.future.push(plain(scripts[selected]));scripts[selected]=restoreScript(h.past.pop());save();render();return true}
  function redo(){const h=histories[selected];if(!h.future.length)return false;h.past.push(plain(scripts[selected]));scripts[selected]=restoreScript(h.future.pop());save();render();return true}
  function spellCode(){return 'SF1.'+btoa(JSON.stringify(plain(scripts[selected]))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_')}
  function spellFile(){return JSON.stringify({format:'Spellforge Loadout',version:1,name:`Spell ${selected+1}`,blocks:plain(scripts[selected])},null,2)}
  function importFile(raw){try{const data=JSON.parse(raw);if(data.format!=='Spellforge Loadout'||data.version!==1||!Array.isArray(data.blocks)||data.blocks.length>maxBlocks()||data.blocks.some(x=>!x||!block(x.id)))throw Error();const locked=data.blocks.find(x=>!owned(x.id));if(locked){tell(`Unlock ${block(locked.id).name} before importing this loadout.`);return false}checkpoint();scripts[selected]=restoreScript(data.blocks);save();tell('Loadout imported into the active slot.');return true}catch{tell('That loadout file is invalid.');return false}}
  function importCode(raw){try{const code=raw.trim();if(!code.startsWith('SF1.')||code.length>9000)throw Error('Invalid Spellforge code');const decoded=JSON.parse(atob(code.slice(4).replace(/-/g,'+').replace(/_/g,'/')));if(!Array.isArray(decoded)||decoded.length>maxBlocks()||decoded.some(x=>!x||typeof x.id!=='string'||!block(x.id)))throw Error('Invalid blocks');const locked=decoded.filter(x=>!owned(x.id));if(locked.length){tell(`Unlock ${block(locked[0].id).name} before importing this spell.`);return false}checkpoint();scripts[selected]=restoreScript(decoded);save();tell('Spell imported into the active slot.');return true}catch{tell('That spell code is invalid.');return false}}
  function saveBlueprint(name){name=String(name||'Untitled spell').trim().slice(0,40);if(!name)return false;blueprints.unshift({name,script:plain(scripts[selected])});blueprints=blueprints.slice(0,40);save();render();return true}
  function loadBlueprint(index){const entry=blueprints[index];if(!entry)return false;const locked=entry.script.find(x=>!owned(x.id));if(locked){tell(`Unlock ${block(locked.id).name} before loading this blueprint.`);return false}checkpoint();scripts[selected]=restoreScript(entry.script);save();render();return true}
  function deleteBlueprint(index){blueprints.splice(index,1);save();render()}
  function purchaseBlock(id){const b=block(id);if(!b||owned(id))return false;if(magic<b.price){tell(`Need ${b.price} Magic for ${b.name}.`);return false}magic-=b.price;permanent.add(id);save();window.SpellAudio?.play('buy');tell(`${b.name} permanently unlocked.`);return true}
  const prerequisites={phaseDash:'dash',aegis:'ward',killSurge:'flow',boltMaster:'focus',burstMaster:'focus',momentum:'stride',bastion:'ward',prosperity:'fortune',overcharge:'focus',specialist:'focus'},prerequisiteRanks={constitution:['vitality',3]};
  function purchaseTalent(id){const t=talents.find(v=>v.id===id);if(!t||talentRank(id)>=talentCap(id))return false;const required=prerequisites[id],rankRequired=prerequisiteRanks[id];if(required&&!talentRank(required)){tell(`${t.name} requires ${talents.find(v=>v.id===required).name} first.`);return false}if(rankRequired&&talentRank(rankRequired[0])<rankRequired[1]){tell(`${t.name} requires ${talents.find(v=>v.id===rankRequired[0]).name} rank ${rankRequired[1]}.`);return false}const price=talentPrice(id);if(magic<price){tell(`Need ${price} Magic for ${t.name}.`);return false}magic-=price;if(id in rankCaps)ranks[id]++;else upgrades.add(id);save();api.onTalentPurchased?.(id);window.SpellAudio?.play('buy');tell(id in rankCaps?`${t.name} rank ${ranks[id]}/${rankCaps[id]} purchased permanently.`:`${t.name} purchased permanently.`);return true}
  function addMagic(amount,reason){const earned=Math.max(0,Math.round(amount*(1+ranks.fortune*.25)));magic+=earned;note=`+${earned} Magic · ${reason}`;$('magicAmount').textContent=magic;api.onMessage?.(note);scheduleSave()}
  function stats(){const vitalityHp=ranks.vitality?40+(ranks.vitality-1)*12:0;return{maxHp:100+vitalityHp+ranks.constitution*10,maxMana:100+ranks.reservoir*30,manaRegen:1+ranks.flow*.3,moveSpeed:upgrades.has('stride')?1.25:1,damage:1+ranks.focus*.16,projectileSpeed:upgrades.has('velocity')?1.35:1,dashCooldown:upgrades.has('dash')?1.4:2.2,waveHeal:12+(ranks.renewal?20+(ranks.renewal-1)*5:0),damageTaken:upgrades.has('ward')?.8:1,critChance:upgrades.has('precision')?.18:0,killMana:upgrades.has('harvest')?12:0,secondWind:upgrades.has('secondWind'),cooldown:upgrades.has('quickcast')?.78:1,cost:upgrades.has('efficiency')?.8:1,phaseDash:upgrades.has('phaseDash'),killSurge:upgrades.has('killSurge'),aegis:upgrades.has('aegis'),boltMaster:upgrades.has('boltMaster'),burstMaster:upgrades.has('burstMaster'),momentum:upgrades.has('momentum'),bastion:upgrades.has('bastion'),prosperity:upgrades.has('prosperity'),overcharge:upgrades.has('overcharge'),specialist:upgrades.has('specialist')}}
  function grantBlock(id){const b=block(id);if(!b||owned(id))return false;permanent.add(id);save();tell(`${b.name} permanently unlocked by a boss achievement.`);return true}
  function estimateCost(multiplier=stats().cost){if(window.SpellArena?.compile){const volleys=window.SpellArena.compile(api.current());return Math.ceil(volleys.reduce((n,v)=>n+window.SpellArena.volleyCost(v)*(v.event==='cast'?(v.control.repeat||1):.3),0)*multiplier)}let elements=[],motions=[],behaviors=[],params={},repeat=1,cost=0;for(const item of scripts[selected]){const b=block(item.id);if(item.value!==undefined)params[item.id]=item.value;if(b.kind==='element'&&!elements.includes(b.id))elements.push(b.id);else if(b.kind==='elasticity'){if(b.id==='straight')motions=[];else if(!motions.includes(b.id))motions.push(b.id)}else if(b.kind==='behavior'){if(b.id==='impact')behaviors=[];else if(!behaviors.includes(b.id))behaviors.push(b.id)}else if(b.kind==='control'){if(b.id==='repeat')repeat=item.value||2}else if(b.kind==='shape'){const one=({bolt:11,fan:19,lance:23,nova:30,scatter:23,orb:21,spiral:26,barrage:27,beam:24,arc:22,ring:27,mine:23}[b.id]||11)+Math.max(0,elements.length-1)*5+Math.max(0,motions.length-1)*4+behaviors.reduce((n,id)=>n+({echo:10,split:6,detonate:7,pierce:5,chain:7,shatter:6,knockback:5,mark:6,absorb:7,fuse:7}[id]||0),0)+(motions.includes('bounce')?Math.max(0,(params.bounce||2)-2)*2:0)+(b.id==='nova'?Math.max(0,(params.nova||8)-8)*2:0);cost+=one*repeat;repeat=1}}return Math.ceil(cost*multiplier)}
  function render(){const root=$('spellPanel');root.innerHTML='';$('magicAmount').textContent=magic;const slots=document.createElement('div');slots.className='spell-slots';scripts.forEach((_,i)=>{const b=document.createElement('button');b.className=i===selected?'active':'';b.textContent=`Spell ${i+1}`;b.onclick=()=>api.select(i);slots.append(b)});root.append(slots);const summary=document.createElement('div');summary.className='summary';summary.textContent=scripts[selected].map(x=>block(x.id).name).join(' → ')||'Empty script';root.append(summary);for(const [mode,label,extra] of [['script','✦ Open Script Editor',''],['upgrades','Browse Permanent Upgrades',' secondary']]){const b=document.createElement('button');b.className='lab-launch'+extra;b.textContent=label;b.onclick=()=>api.openEditor?.(mode);root.append(b)}const f=document.createElement('div');f.className='spell-note';f.textContent=note||`Script capacity: ${scripts[selected].length} / ${maxBlocks()} blocks.`;root.append(f);api.onRender?.()}
  const api={definitions,talents,defaults,parameters,scripts,block,owned,statsOwned:id=>talentRank(id)>=talentCap(id),talentRank,talentCap,talentPrice,maxBlocks,estimateCost,grantBlock,prerequisites,prerequisiteRanks,get selected(){return selected},get magic(){return magic},get lastNote(){return note},get blueprints(){return blueprints},current(){return scripts[selected].map(x=>({...x,kind:block(x.id).kind}))},select(i){if(window.SpellArena?.getGame()?.mode==='oneslot'&&i!==0){tell('One Slot challenge: only Spell 1 is available.');return}selected=Math.max(0,Math.min(2,i));render()},insertBlock,moveBlock,removeBlock,moveRange,removeRange,duplicateRange,undo,redo,spellCode,importCode,spellFile,importFile,saveBlueprint,loadBlueprint,deleteBlueprint,setParam,purchaseBlock,purchaseTalent,addMagic,stats,onMessage:null,onRender:null,onEditorChange:null,onTalentPurchased:null,onUnlockRequest:null,openEditor:null};
  window.SpellSystem=api;window.addEventListener?.('beforeunload',save);render();
})();
